### ISSUE TITLE
Beta value from mtag results.

### ISSUE THREAD

**Issue by gnarw** [omeed-maghzian/mtag#10]
When running MTAG I have noticed that I´m getting much lower beta values (mtag_beta) for each trait. 
For example, for one trait a SNP has an effect of -0.09 but the mtag_beta is -0.01 for that same trait.
This might of course depend on many things, e.g the traits used.
After reading the MTAG paper (and supplementary information) and the tutorial on github I´m no closer in understanding how to interpret the mtag_beta.

When running a single trait in MTAG (this is actually possible without getting warning or error messages) the mtag_beta is also much lower than the original beta value for that single trait. Would you not expect mtag_beta to be identical to the trait´s beta value when running only one trait ?

Here is the log file from the single trait MTAG run:
[ST.txt](https://github.com/omeed-maghzian/mtag/files/1647398/ST.txt)

**Comment by omeed-maghzian** [comment]
@gnarw Are the GWAS betas you are comparing to the MTAG betas standardized? The column `mtag_beta` is not standardized by default (`--std_betas` is make the betas standardized), so you might be comparing two betas columns that have different units. 

In any case, for the single trait run of MTAG, your `z` and `mtag_z` column in the results file should be identical (the summary table in the log file suggests this to be true). Can you confirm that this is the case?

**Comment by gnarw** [comment]
The beta for the trait I am running has a mean of -0.00124 and standard deviation of 0.0406.
The mtag_beta has a mean of -0.000126 and standard deviation of 0.006100
If I use the --std_betas I get mtag_beta with a mean of -1.8234e-5 and standard deviation of 0.0019

As an example, for one SNP the following applies.
Trait: beta = -0.1347, z = -6.7905
MTAG: z = -6.79048, mtag_beta = -0.020, mtag_z = -6.76755
MTAG with --std_betas: z  = -6.79048, mtag_beta = -0.0124, mtag_z = -6.76755

**Comment by paturley** [comment]
In your original GWAS, was the phenotype you are using standardized? The
beta estimate you have there seems very large to me for a trait with
variance one. Correct me if I'm wrong, Omeed, but I think that the MTAG
betas assume that the phenotype had been normalized. If it wasn't and you
want beta to be in the same units as before, I would simply multiply the
betas by the standard deviation of the original phenotype, and I think that
you should find that it is more-or-less that same as the input summary
statistics.

**Comment by paturley** [comment]
In any case, the z-stats and p-values should be valid since the standard
errors would have also been scaled accordingly.

**Comment by omeed-maghzian** [comment]
@paturley That's right, `mtag` assumes the phenotypes have been normalized.

**Comment by gnarw** [comment]
@paturley  For the example SNP the trait beta = -0.1347 while the mtag_beta = -0.020
The SNP standard deviation for the trait (in the original GWAS data) is very small. So multiplying two small numbers makes an ever smaller number.
Is is possible that you mean I should multiply the mtag_z with the standard deviation of the original GWAS to obtain an mtag_beta value that has the same units as beta in the original GWAS data ?

**Comment by paturley** [comment]
Sorry. I meant you should multiply the MTAG beta by the standard deviation
of the phenotype. Does the phenotype have a sd of about 7?

**Comment by gnarw** [comment]
@paturley I only have access to the GWAS data for the trait I´m working on. The standard deviation for the GWAS beta values is 0.0406. Multiplying the mtag_beta with the standard deviation is -0.020 * 0.0406 = 0.000812. This is not close to the original GWAS beta value for this example SNP.

**Comment by paturley** [comment]
The standard deviation of the GWAS beta values is not the same as the
standard deviation of the phenotype. Does the paper from which the summary
statistics come not report the s.d. of the phenotype? An easy way to verify
if it's the scaling of the phenotype that is causing the problem is if
beta_GWAS/beta_MTAG is approximately constant for all SNPs.

**Comment by gnarw** [comment]
1. The GWAS I have been working on is for a binary trait (outcome = 1/0). The standard deviation for the outcome is 0.237.
Multiplying the mtag_beta with the standard deviation for the phenotype does not bring the mtag_beta closer to the SNP beta.

2. The beta_GWAS/beta_MTAG is approximately normally distributed between about 4 to 15. Is that approximately constant ?, I don´t know.

3. I have another question. The z-score (that MTAG needs) is computed by beta/se. 
This is what I am doing.
The z-score I compute from the GWAS is very similar to the mtag_z value. I see that the mtag_z is computed from mtag_beta/mtag_se.
The mtag_beta and mtag_se are both scaled down, compared to the GWAS. Using all your valuable comments and help it´s still not clear how to interpret the mtag_beta.
Appreciate your help.

**Comment by paturley** [comment]
Ah. I think I may see what the problem is. The MTAG SEs are assumed to be
1/sqrt(N*2*p*(1-p) ). In a case-control study, this is only true if N is
the effective N.

I recommend you replace the N column with the value 1/( 2*p*(1-p)*(SE^2) )
and see if that solves the problem.

Relatedly, Omeed, it would be good if we could add an option to MTAG so it
accepts betas and SEs rather than Zs and Ns. It would be a lot more robust
to these sorts of problems.

**Comment by gnarw** [comment]
I replaced the N column  in the input to MTAG with the value 1/( 2*p*(1-p)*(SE^2) )
This did not solve my problem I have with the mtag_beta and mtag_se values.
I have included a file with the output from mtag, for a single example SNP. The GWAS data for the same SNP is also included.
[example.txt](https://github.com/omeed-maghzian/mtag/files/1674104/example.txt)

**Comment by paturley** [comment]
I think there must be an error in the code where you replace the N column.
For this SNP, 1/( 2*p*(1-p)*(SE^2) ) = 6589.27. It looks like from your
MTAG results, you are getting something like 1.14e14.

**Comment by gnarw** [comment]
I just don´t see what I´m doing wrong.
I´m using R to create the input file to mtag.
Here is how I´m replacing the N column.
df$n = 1/(2*df$pval*(1-df$pval)*(df$se^2))

**Comment by paturley** [comment]
Sorry. "p" was meant to be the minor allele frequency. Not the p-value.

**Comment by gnarw** [comment]
This solved the problem I had with the mtag_beta values.
Now, the output makes more sense.
Thanks for you help and patience.

**Comment by pjordab** [comment]
Hi dear developers,

I'm trying to calculate the n effective of my sumstats, in the case the phenotype is not been normalized which I think it is the case: 

**Beta:**
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-3.916580 -0.009670  0.000000 -0.000282  0.009600  3.335030
**SE:**
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00765 0.00926 0.01279 0.02090 0.02324 7.74015
**Z:**
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.
-21.417800  -0.676904   0.000000  -0.003476   0.671840  14.795095

Is it appropiate to use the following formula:

Neff = 4 / (1 / cases + 1 / controls) ?

or how should I adapt this other one: 1/( 2*p*(1-p)*(SE^2) ) ?

Thank you very much!

Paloma

**Comment by paturley** [comment]
HI Paloma,

Either of those should be OK. If you wanted to use the second one, I think
that the numerator would been to be the variance of the phenotype, which is
q(1-q) for a binary phenotype with prevalence q.

Patrick

**Comment by pjordab** [comment]
Thanks so much Patrick!  Do you refer to the prevalence in the sample (cases/total sample size)?
So:    q(1-q)/( 2p(1-p)*(SE^2) )

**Comment by paturley** [comment]
I don't know that I have strong preferences. I haven't tested the two
options rigorously, so I'm not sure if I would expect one to be better than
the other. I suspect that your ultimate results would be fairly similar
either way.

**Comment by pjordab** [comment]
Thank you!!

Unfortunately, I do not get the same results. While doing: 

gwas$prev <-  gwas$cases /(gwas$cases + gwas$controls)
gwas$neff_se <- (gwas$prev * (1-gwas$prev))/(2 * gwas$maf * (1-gwas$maf) * (gwas$se^2))
gwas$neff <- 4 / (1 / gwas$cases  + 1 / gwas$controls)) 

> head(gwas)
        snpid chr   bpos a1 a2    freq    beta      se     pval      sample_size cases
1 rs561255355   1 569406  G  A 0.99858 0.05191 0.27358 0.849496 154959 71602
2 rs143225517   1 751756  C  T 0.14418 0.00546 0.01416 0.699604 254199 71602

  controls      prev         z     maf   neff_se     neff
1   260875 0.2153593 0.1897434 0.00142  796.0943 224727.4
2   260875 0.2153593 0.3855932 0.14418 3414.9979 224727.4
3   260875 0.2153593 0.2289855 0.17332 3096.4218 224727.4

Ratio: gwas$neff_se/gwas$neff
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.0001896 0.0192062 0.0215219 0.0205033 0.0226058 0.0413526

If don't see the bug... Thank you very much for your time and help!

**Comment by paturley** [comment]
Hmm. I'm surprised by how low your neff_se values are. I suspect it's
because the SE is not in percentage point units. The other N formula should
work fine though. It wont always match the se-based formula, but it is less
sensitive to misspecified units and it should be close enough. The LDSC
step of MTAG should resolve any differences between the two.
