### ISSUE TITLE
Outputting FDR

### ISSUE THREAD

**Issue by tjmeyers** [omeed-maghzian/mtag#11]
Dear Authors, 

I was able to run your python script without errors. However, the output doesn't include information about false-discovery rate (FDR), although this seems to be calculated in the script ('return FDR_val'). Are the MTAG_results traits files already filtered by FDR? Thank you.

**Comment by omeed-maghzian** [comment]
Hi Travis, 

Thanks for this -- it is an important point. Depending on the number of traits and the fineness of the grid that is used to make the approximation (see `--intervals`), the FDR calculation may take a potentially long time. We've made it into a separate option, `--fdr`, that you need to invoke when running MTAG. The program would proceed as normal (meaning that it would replicate the log that you've already seen), but at the very end it would calculate and display the FDR based on the framework used in the Supplementary Note of the Nature Genetics paper. 

I am sad to admit that I have neglected writing a tutorial that walks through the FDR calculation. I will try to have one up in the next few weeks. The FDR option group under the help listing (`-h`) should, however, provide enough guidance to produce FDR calculations. If you are using a large number of traits, we recommend using `--n_approx` option, which uses an approximation of the summary statistic sample sizes to speed up computation. Please let us know if you come across anything confusing.
 
And, just for clarification, MTAG doesn't do any filtering of the traits based on the FDR. The software can perform the calculations, but it is ultimately up to the user to decide whether the MTAG estimator is well-suited for their multi-trait analysis.

**Comment by tjmeyers** [comment]
Thank you, I should have checked -h first but I appreciate your insight.
