### ISSUE TITLE
About Beta and OR

### ISSUE THREAD

**Issue by xiangboyulan** [omeed-maghzian/mtag#14]
Hi everone,

I have two results of GWASs, one is the Beta and another is OR, could I used the MTAG program to analyze them? Thanks!

Bo

**Comment by paturley** [comment]
Hi Bo,

You should not pass ORs into MTAG since an assumption of MTAG is that the
summary statistic estimates are mean-zero and ORs are mean-one. I would
first convert those statistics to betas on the liability scale.

Best,
Patrick
