### ISSUE TITLE
reference panel

### ISSUE THREAD

**Issue by jineexia** [omeed-maghzian/mtag#17]
The reference panel implemented in MTAG is 1000G CEU.  Is it possible to use other reference panel such as 1000G ASW or lager reference panel of the Haplotype Reference Consortium (HRC)? How should I generate the reference panel information needed for MTAG computation?  Thank you very much!

**Comment by omeed-maghzian** [comment]
Hi @jineexia ,

Yes, you can use other reference panels. The reference panel is only used during the estimation of the residual variance covariance matrix with LD Score Regression. You can use the `--ld_ref_panel` to pass the location of another reference panel (split by chromosome). The argument to this option is passed to the `--ref-ld-chr` and `--w-ld-chr` options in [ldsc](https://github.com/bulik/ldsc), so you check to make sure the reference panel is compatible with that program first. I copied the relevant option from the `-h` help file below:

```
--ld_ref_panel FOLDER_PATH
                        Specify folder of the ld reference panel (split by
                        chromosome) that will be used in the estimation of the
                        error VCV (sigma). This option is passed to --ref-ld-
                        chr and --w-ld-chr when running LD score regression.
                        The default is to use the reference panel of LD scores
                        computed from 1000 Genomes European subjects
                        (eur_w_ld_chr) that is included with the distribution
```

**Comment by rkwalters** [comment]
Hi,
To expand on this: in addition to the 1000G EUR panel distributed with MTAG, there are 1000G EAS scores computed for ldsc available for download here <https://data.broadinstitute.org/alkesgroup/LDSCORE/> (file “eas_ldscores.tar.bz2”). For other reference panels, you can find a tutorial with information on computing the required LD scores files from your desired reference panel here <https://github.com/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial>, with more details on considerations for filtering, etc in the Online Methods of Bulik-Sullivan et al. 2015 <https://www.ncbi.nlm.nih.gov/pubmed/25642630> and the Supplement of Finucane et al. 2015 <https://www.ncbi.nlm.nih.gov/pubmed/26414678>.
Cheers,
Raymond
