### ISSUE TITLE
Questions concerning input files

### ISSUE THREAD

**Issue by julyankb** [omeed-maghzian/mtag#18]
I am attempting to use the MTAG software to jointly analyze two sets of GWAS summary statistics. 
I have updated all the required packages and have it running successfully on the neuroticism and subjective well-being example data sets from the tutorial.

However, when I try to run it on my own set of GWAS's (2 of them), I am getting an error that leaves me unsure about how to proceed.

Considering that the software worked on the example data sets, I suspect that the issue arises from one of two sources:
1) I am not building/formatting my input data sets correctly.
2) A certain assumption about the data does not hold in one or both of my GWAS's.

To elaborate:

1) I use the following columns in my input file:
"snpid    chr    bpos    a1    a2    freq    z    pval    n". 
I have no doubts about the snpid, chr, bpos, a1, a2 columns but I suspect that there may be an issue with one or both of the remaining two columns.
Z-scores for each SNP is z = beta/standard error and the SNP sample sizes n = number of individuals in the GWAS (341,450 in each GWAS).
I am not sure that "snp sample sizes" represents the number of individuals in the cohort but this was my best guess after doing some research.

2) If there are no issues with the input columns, then my next guess would be that there are statistical differences between our data sets that were perhaps not accounted for in the software.

I have attached the log file. Hopefully it can help you direct me toward a solution.
Log file:
[mtag.log](https://github.com/omeed-maghzian/mtag/files/1823151/mtag.log)

Thanks in advance

**Comment by julyankb** [comment]
Resolved. Input file contained NaN values under 'z' column. Did not realize that there were some 'nan' values outputted by BOLT-LMM for std. error.

**Comment by paturley** [comment]
Great. Glad you figured it out before we did. In future versions, we'll try
to make it robust to issues like that.
