### ISSUE TITLE
Array must not contain infs or NaNs error

### ISSUE THREAD

**Issue by erampers** [omeed-maghzian/mtag#22]
I am getting a message that I interpret to mean that you cannot have missing pvalues for SNPs that overlap the two trait summary files.
Is this a correct assumption?
The input file example is below and so is the error message ).

snpid   chr     bpos    a1      a2      freq    z       pval    n
rs531646671     1       14599   A       T       0.02298 -0.8175 0.414   544
rs541940975     1       14604   G       A       0.02298 -0.8175 0.414   544
        1       14610   C       T       0.02206 -0.9074 0.3646  544
rs548251696     1       15776   T       A       0.00814 .       .       553
rs2691315       1       15820   T       G       0.47232 -0.0544 0.9567  542
        1       15834   T       C       0.00091 .       .       552
rs556025965     1       15849   T       C       0.00271 .       .       553
        1       15884   C       G       0.00096 .       .       522
 
 
 
2018/04/03/09:55:57 AM Beginning estimation of Omega ...
2018/04/03/09:55:57 AM Using GMM estimator of Omega ..
2018/04/03/09:55:59 AM Checking for positive definiteness ..
2018/04/03/09:55:59 AM 
Traceback (most recent call last):
  File "mtag-master/mtag.py", line 1348, in <module>
    mtag(args)
  File "mtag-master/mtag.py", line 1233, in mtag
    args.omega_hat = estimate_omega(args, Zs[not_SA], Ns[not_SA], args.sigma_hat)
  File "mtag-master/mtag.py", line 690, in estimate_omega
    return _posDef_adjustment(gmm_omega(Zs,Ns,sigma_LD))
  File "mtag-master/mtag.py", line 417, in _posDef_adjustment
    if is_pos_semidef(mat):
  File "mtag-master/mtag.py", line 416, in <lambda>
    is_pos_semidef = lambda m: np.all(np.linalg.eigvals(m) >= 0)
  File "/hpcf/apps/python/install/2.7.12/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 904, in eigvals
    _assertFinite(a)
  File "/hpcf/apps/python/install/2.7.12/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 216, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
LinAlgError: Array must not contain infs or NaNs
2018/04/03/09:55:59 AM Analysis terminated from error at Tue Apr  3 09:55:59 2018
2018/04/03/09:55:59 AM Total time elapsed: 15.0m:38.64s

**Comment by huilisabrina** [comment]
Hi,

The missing p-values does not necessarily lead to this reported error, as MTAG uses Z's and N's (and Sigma_LD from ldsc) to estimate the Omega. But there are a few other things to check:
- The sample size is really small in your data. This can lead to inaccurate estimation of Omega. Could you attach the full log file from your run? 
- Could you try running bi-variate LDSC to check the genetic correlation between the two traits? 
- Some of the old/closed [issues](https://github.com/omeed-maghzian/mtag/issues?q=is%3Aissue+is%3Aclosed) might be helpful to go through. It's always important to do QC before using MTAG. Note that there are also missing snpid in the data you sent.

Thanks,
Hui

**Comment by erampers** [comment]
Thanks! I removed the lines with missing pvalues and it ran and produced an outcomes file.


Evadnie

________________________________

**Comment by paturley** [comment]
As Hui indicated, the mission p-value would have been fine, but it looks
like the missing z-scores are what likely caused your problem. Glad it is
working better for you now.

Best,
Patrick

**Comment by paturley** [comment]
More important than the sample size is the mean chi2 statistic of your sets
of summary statistics. If you use MTAG to combine summary statistics where
the sample size is low in one analysis and high in the other, it can lead
to a increase Type-I error and false discovery rate. There is code build
into the software that will calculate the maxFDR for your particular
application, which can be thought of as a worst-case-scenario false
discovery rate.

**Comment by erampers** [comment]
Thank you for the explanation! I will take a look at the maxFDR value for the results I generated.

Evadnie

**Comment by erampers** [comment]
Hello again,

Thank you very much for the responsiveness to my questions.
Sorry to bother you again but I do want to make sure I’m interpreting these data results correctly and there are others in my group wanting to test it on their datasets as well. We have a journal club scheduled to review the paper but I wanted to run a test case first in preparation.

This is what I ran:

module load python/2.7
module load mtag/0.9

python mtag-master/mtag.py  \
        --sumstats hbf_unconditional.epacts.ready.noNA.nomissing,mcv_unconditional.epacts.ready.noNA.nomissing \
        --out ./evadnie.1NS \
        --n_min 0.0 \
      --stream_stdout &

Where hbf_unconditional.epacts.ready.noNA.nomissing and mcv_unconditional.epacts.ready.noNA.nomissing are both text files with summary statistics for two traits that are correlated.


My log file is below.
I interpret this as meaning that the sample size is too small and producing results that are identical to what I would achieve by standard GWAS alone. Is this the correct interpretation or are some parameters not fully indicated?
Also, where is the maxFDR usually output to?

  Trait                 N (max)  N (mean)  # SNPs used  GWAS mean chi^2  MTAG mean chi^2  GWAS equiv. (max) N
1  ...y.noNA.nomissing  567      566       15104261     0.997            0.996            687
2  ...y.noNA.nomissing  557      556       15104261     0.988            0.988            599



[erampers@nodecn262  UNCONDITIONAL]$ more *log
2018/04/03/07:40:49 PM
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<>
<> MTAG: Multi-trait Analysis of GWAS
<> Version: 1.0.7
<> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
<> Harvard University Department of Economics / Broad Institute of MIT and Harvard
<> GNU General Public License v3
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<> Note:  It is recommended to run your own QC on the input before using this program.
<> Software-related correspondence: maghzian@nber.org
<> All other correspondence: paturley@broadinstitute.org
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


Calling ./mtag.py \
--stream-stdout  \
--n-min 0.0 \
--sumstats hbf_unconditional.epacts.ready.noNA.nomissing,mcv_unconditional.epacts.ready.noNA.nomissing \
--out ./evadnie.1NS

2018/04/03/07:40:49 PM Beginning MTAG analysis...
2018/04/03/07:41:22 PM Read in Trait 1 summary statistics (18438750 SNPs) from hbf_unconditional.epacts.ready.noNA.nomissing ...
2018/04/03/07:41:22 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:41:22 PM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/04/03/07:41:22 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:41:22 PM Interpreting column names as follows:
2018/04/03/07:41:22 PM snpid:   Variant ID (e.g., rs number)
n:      Sample size
a1:     Allele 1, interpreted as ref allele for signed sumstat.
pval:   p-Value
a2:     Allele 2, interpreted as non-ref allele for signed sumstat.
z:      Directional summary statistic as specified by --signed-sumstats.

2018/04/03/07:41:23 PM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/04/03/07:41:49 PM Read 18438750 SNPs from --sumstats file.
Removed 1432134 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 1801287 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
15205329 SNPs remain.
2018/04/03/07:42:04 PM Removed 80 SNPs with duplicated rs numbers (15205249 SNPs remain).
2018/04/03/07:42:06 PM Removed 21594 SNPs with N < 378.0 (15183655 SNPs remain).
2018/04/03/07:42:47 PM Median value of SIGNED_SUMSTATS was -0.0044, which seems sensible.
2018/04/03/07:42:48 PM Dropping snps with null values
2018/04/03/07:42:50 PM
Metadata:
2018/04/03/07:42:50 PM Mean chi^2 = 1.001
2018/04/03/07:42:50 PM WARNING: mean chi^2 may be too small.
2018/04/03/07:42:50 PM Lambda GC = 1.001
2018/04/03/07:42:50 PM Max chi^2 = 112.79
2018/04/03/07:42:50 PM 32 Genome-wide significant SNPs (some may have been removed by filtering).
2018/04/03/07:42:50 PM
Conversion finished at Tue Apr  3 19:42:50 2018
2018/04/03/07:42:50 PM Total time elapsed: 1.0m:28.27s
2018/04/03/07:43:15 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:43:15 PM Munging of Trait 1 complete. SNPs remaining:      15184439
2018/04/03/07:43:15 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/04/03/07:43:46 PM Trait 1: Dropped 784 SNPs for duplicate values in the "snp_name" column
2018/04/03/07:44:19 PM Read in Trait 2 summary statistics (18351868 SNPs) from mcv_unconditional.epacts.ready.noNA.nomissing ...
2018/04/03/07:44:19 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:44:19 PM Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/04/03/07:44:19 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:44:19 PM Interpreting column names as follows:
2018/04/03/07:44:19 PM snpid:   Variant ID (e.g., rs number)
n:      Sample size
a1:     Allele 1, interpreted as ref allele for signed sumstat.
pval:   p-Value
a2:     Allele 2, interpreted as non-ref allele for signed sumstat.
z:      Directional summary statistic as specified by --signed-sumstats.

2018/04/03/07:44:20 PM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/04/03/07:44:45 PM Read 18351868 SNPs from --sumstats file.
Removed 1428699 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 1794948 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
15128221 SNPs remain.
2018/04/03/07:45:03 PM Removed 82 SNPs with duplicated rs numbers (15128139 SNPs remain).
2018/04/03/07:45:05 PM Removed 21703 SNPs with N < 371.333333333 (15106436 SNPs remain).
2018/04/03/07:45:46 PM Median value of SIGNED_SUMSTATS was -0.0003, which seems sensible.
2018/04/03/07:45:47 PM Dropping snps with null values
2018/04/03/07:45:48 PM
Metadata:
2018/04/03/07:45:48 PM Mean chi^2 = 1.007
2018/04/03/07:45:48 PM WARNING: mean chi^2 may be too small.
2018/04/03/07:45:49 PM Lambda GC = 1.007
2018/04/03/07:45:49 PM Max chi^2 = 26.486
2018/04/03/07:45:49 PM 0 Genome-wide significant SNPs (some may have been removed by filtering).
2018/04/03/07:45:49 PM
Conversion finished at Tue Apr  3 19:45:49 2018
2018/04/03/07:45:49 PM Total time elapsed: 1.0m:29.81s
2018/04/03/07:46:13 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/04/03/07:46:13 PM Munging of Trait 2 complete. SNPs remaining:      15107230
2018/04/03/07:46:13 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/04/03/07:46:46 PM Trait 2: Dropped 794 SNPs for duplicate values in the "snp_name" column
2018/04/03/07:47:18 PM Trait 2 summary statistics:       15104290 SNPs remaining merging with previous traits.
2018/04/03/07:47:33 PM Dropped 29 SNPs due to inconsistent allele pairs from phenotype 2. 15104261 SNPs remain.
2018/04/03/07:47:42 PM ... Merge of GWAS summary statistics complete. Number of SNPs:    15104261
2018/04/03/07:47:59 PM Using 12744570 SNPs to estimate Omega (2359691 SNPs excluded due to strand ambiguity)
2018/04/03/07:47:59 PM Estimating sigma..
2018/04/03/07:51:22 PM Checking for positive definiteness ..
2018/04/03/07:51:22 PM Sigma hat:
[[1.007 0.153]
[0.153 1.023]]
2018/04/03/07:51:22 PM Mean chi^2 of SNPs used to estimate Omega is low for some SNPsMTAG may not perform well in this situation.
2018/04/03/07:51:23 PM Beginning estimation of Omega ...
2018/04/03/07:51:23 PM Using GMM estimator of Omega ..
2018/04/03/07:51:24 PM Checking for positive definiteness ..
2018/04/03/07:51:24 PM matrix is not positive definite, performing adjustment..
2018/04/03/07:51:24 PM Warning: max number of iterations reached in adjustment procedure. Sigma matrix used is still non-positive-definite.
2018/04/03/07:51:24 PM Completed estimation of Omega ...
2018/04/03/07:51:24 PM Beginning MTAG calculations...
2018/04/03/07:53:14 PM  ... Completed MTAG calculations.
2018/04/03/07:53:14 PM Writing Phenotype 1 to file ...
2018/04/03/07:55:13 PM Writing Phenotype 2 to file ...
2018/04/03/07:57:12 PM
Summary of MTAG results:
------------------------
  Trait                 N (max)  N (mean)  # SNPs used  GWAS mean chi^2  MTAG mean chi^2  GWAS equiv. (max) N
1  ...y.noNA.nomissing  567      566       15104261     0.997            0.996            687
2  ...y.noNA.nomissing  557      556       15104261     0.988            0.988            599

Estimated Omega:
[[-6.373e-06  1.453e-10]
[ 1.453e-10 -2.135e-05]]

Estimated Sigma:
[[1.007 0.153]
[0.153 1.023]]

**Comment by paturley** [comment]
It looks to me like your sample is too small for MTAG to produce meaningful
results. Look at your estimated Omega matrix at the end of the log file.
The diagonal has negative values, implying a negative variance of SNP
effects and a negative heritability. Relatedly, I generally use (1 -
mean(chi2) ) as a measure of the power of the GWAS, and in your case, it
looks like your mean chi2 statistic doesn't even exceed one.

**Comment by erampers** [comment]
Yes, I agree. This is more or less what I thought regarding sample size.
I’ll read up on the OMEGA interpretation however thank you for the explanation.

Evadnie

**Comment by huilisabrina** [comment]
Hi @erampers ,

Just wanted to follow up and see if your issue has be resolved now. If so, feel free to close the issue.

Thanks!
Hui
