### ISSUE TITLE
p-value threshold in maxFDR calculation

### ISSUE THREAD

**Issue by paturley** [omeed-maghzian/mtag#23]
I’m having a bit of problems getting the FDR step to run. It works fine with the standard p-value threshold, but it chokes if I provide an alternative threshold using –p_sig (which is relevant to do in our case). Specifying 5.0e-8, 1.667e-8 and 0.0000000167 results in a TypeError: unsupported operand type(s) for /: ‘str’ and ‘float’. Any ideas why that is? – I can send you the traceback if you need it.

**Comment by huilisabrina** [comment]
Hi @paturley (and Jakob),

Which one of the following way did you change it to:
1. p_sig="1.667e-8"
2. p_sig= 1.667e-8

The second one is correct. Using the first one will lead to the TypeError you specified. Also, it'd be helpful if you can attach the full log file and traceback. I'm guessing that this error happens in the following line?
```
def compute_fdr(prob, t, omega, sigma, S, Ns,N_counts, p_threshold):
    z_threshold = scipy.stats.norm.isf(p_threshold / 2.)
```
The `z_threshold` calculation breaks if you're dividing a string with a float. Hope this works. I have tested changing the `p_sig` threshold using the specified numbers (_i.e._ 5.0e-08,_ 1.667e-8 and 0.0000000167) and maxFDR ran just fine. 

Best,
Hui

**Comment by rkwalters** [comment]
Hi all,
I think this should be avoidable by having MTAG's arg parsing specify "type=float" for the p_sig argument? (At line 1322 of mtag.py)
Cheers,
Raymond

**Comment by paturley** [comment]
Great. Thanks, Raymond.

Hui, can we make that fix that Raymond recommended and push out a new
version?

**Comment by huilisabrina** [comment]
@rkwalters Thanks for pointing that out. @paturley yes I can add a commit for that!
