### ISSUE TITLE
ValueError: DLASCL parameter

### ISSUE THREAD

**Issue by rafet2005** [omeed-maghzian/mtag#27]
Hi,
I'm trying to run MTAG, but having some issues. I use the following command to run it. python2.7 ../software/mtag/mtag.py 
--sumstats Medium_Small_LDL_all.txt_head_clean,Medium_Large_VLDL_all.txt_head_clean  --out ./out_test  
--stream_stdout &

I'm getting the following error:

<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<>
<> MTAG: Multi-trait Analysis of GWAS 
<> Version: 1.0.7
<> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
<> Harvard University Department of Economics / Broad Institute of MIT and Harvard
<> GNU General Public License v3
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<> Note:  It is recommended to run your own QC on the input before using this program. 
<> Software-related correspondence: maghzian@nber.org 
<> All other correspondence: paturley@broadinstitute.org 
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Calling ./mtag.py \
--stream-stdout  \
--sumstats Medium_Small_LDL_all.txt_head_clean,Medium_Large_VLDL_all.txt_head_clean \
--out ./out_test 

Beginning MTAG analysis...
Read in Trait 1 summary statistics (520409 SNPs) from Medium_Small_LDL_all.txt_head_clean ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
. done
Read 520409 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
520409 SNPs remain.
Removed 49 SNPs with duplicated rs numbers (520360 SNPs remain).
Removed 0 SNPs with N < 548.0 (520360 SNPs remain).
Median value of SIGNED_SUMSTATS was -0.000250662830088, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 0.994
WARNING: mean chi^2 may be too small.
Lambda GC = 1.001
Max chi^2 = 27.354
0 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Tue Apr 24 13:41:30 2018
Total time elapsed: 16.57s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 1 complete. SNPs remaining:	 520409
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Trait 1: Dropped 49 SNPs for duplicate values in the "snp_name" column
Read in Trait 2 summary statistics (507214 SNPs) from Medium_Large_VLDL_all.txt_head_clean ...
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Interpreting column names as follows:
snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
. done
Read 507214 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
507214 SNPs remain.
Removed 41 SNPs with duplicated rs numbers (507173 SNPs remain).
Removed 0 SNPs with N < 582.0 (507173 SNPs remain).
Median value of SIGNED_SUMSTATS was 0.0160431091306, which seems sensible.
Dropping snps with null values

Metadata:
Mean chi^2 = 0.982
WARNING: mean chi^2 may be too small.
Lambda GC = 0.971
Max chi^2 = 17.973
0 Genome-wide significant SNPs (some may have been removed by filtering).

Conversion finished at Tue Apr 24 13:41:46 2018
Total time elapsed: 14.1s
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Munging of Trait 2 complete. SNPs remaining:	 507214
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Trait 2: Dropped 41 SNPs for duplicate values in the "snp_name" column
Trait 2 summary statistics: 	 505198 SNPs remaining merging with previous traits.
Dropped 4 SNPs due to inconsistent allele pairs from phenotype 2. 505194 SNPs remain.
... Merge of GWAS summary statistics complete. Number of SNPs:	 505194
Using 430221 SNPs to estimate Omega (74973 SNPs excluded due to strand ambiguity)
Estimating sigma..
(array([], dtype=int64), array([], dtype=int64))
(array([14046]), array([0]))
(array([], dtype=int64), array([], dtype=int64))
(array([    0,     0,     1, ..., 71699, 71700, 71700]), array([0, 1, 0, ..., 1, 0, 1]))
(array([    0,     1,     2, ..., 71698, 71699, 71700]), array([0, 0, 0, ..., 0, 0, 0]))
(array([    0,     1,     2, ..., 71698, 71699, 71700]), array([0, 0, 0, ..., 0, 0, 0]))
On entry to DLASCL parameter number 4 had an illegal value
Traceback (most recent call last):
  File "../software/mtag/mtag.py", line 1348, in <module>
    mtag(args)
  File "../software/mtag/mtag.py", line 1211, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "../software/mtag/mtag.py", line 393, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/sumstats.py", line 444, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, k, i)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/sumstats.py", line 592, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/regressions.py", line 688, in __init__
    slow=slow, twostep=twostep)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/regressions.py", line 213, in __init__
    x, yp, update_func, n_blocks, slow=slow, w=initial_w)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/irwls.py", line 66, in __init__
    x, y, update_func, n_blocks, w, slow=slow, separators=separators)
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/irwls.py", line 113, in irwls
    new_w = np.sqrt(update_func(cls.wls(x, y, w)))
  File "/media/rafet/5e29cbfd-eff8-4007-8e15-c06b94f09007/software/mtag/ldsc_mod/ldscore/irwls.py", line 164, in wls
    coef = np.linalg.lstsq(x, y)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 1919, in lstsq
    0, work, lwork, iwork, 0)
ValueError: On entry to DLASCL parameter number 4 had an illegal value

What do you think could cause this.

I run the data you have in the gitHub it works fin! 

Thank you for your help.

**Comment by paturley** [comment]
I suspect that it is due to the very small mean chi2 statistic you use in
your data. MTAG needs to use summary statistics that are sufficiently well
powered in order to estimate the heritability and genetic correlation
before it can run MTAG, and a mean chi2<1 implies a negative heritability.
To be clear, I don't think that the heritability of your phenotypes are
actually negative, but I think that your sample sizes are too small to get
a precise estimate of the actual heritability.

**Comment by rafet2005** [comment]
Thank you.
Is there a minimum sample size. Our sample size is 900

Thanks.

**Comment by paturley** [comment]
There is no minimum sample size since it depends on the heritability as
well. The more helpful stat is the mean chi2 statistic. We haven't tested
scenarios with a mean chi2 statistic under 1.1, but even at that level, the
results are a bit unstable.

**Comment by huilisabrina** [comment]
Hi @rafet2005 ,

Just wanted to follow up and see if you have resolved the issue. If so, feel free to close the issue. Thanks!

Best,
Hui

**Comment by huilisabrina** [comment]
Hi @rafet2005 ,

It's better to use the complete list of summary statistics from different traits. I think you'll lose a lot of information if you just use the top hits from each trait as they may not overlap. MTAG can use the information from different sumstats to increase the power to better detect variants with the most impact on each phenotype. Also MTAG only uses the subset of the SNPs that are present in all the sumstats inputs you provide, so any initial restriction would lead to even fewer SNPs.

Best,
Hui

**Comment by rafet2005** [comment]
Thank you.
