### ISSUE TITLE
Problem with --ld_ref_panel flag

### ISSUE THREAD

**Issue by lcastanoduque0105** [omeed-maghzian/mtag#28]
I am currently trying to run a meta analysis of GWAS for rice.

Because LD score for rice is different from the 1000 Genomes that is used in MTAG as reference, I used ldsc to calculate the LD scores.

I was finally able to get it running but there is a very simple error that I am really not sure how to solve and there is no information in the wiki, tutorials, google groups or anything.

My organism has only 12 chromosomes but MTAG looks for chr13. I have all the LD scores up to chr12 but when I am running MTAG the following error appears:

2018/05/01/10:47:56 AM Trait 2 summary statistics:       693501 SNPs remaining merging with previous traits.
2018/05/01/10:47:57 AM ... Merge of GWAS summary statistics complete. Number of SNPs:    693501
2018/05/01/10:47:57 AM Using 610674 SNPs to estimate Omega (82827 SNPs excluded due to strand ambiguity)
2018/05/01/10:47:57 AM Estimating sigma..
2018/05/01/10:47:59 AM [Errno 2] No such file or directory: '/work/lmc86/META/LD_data/LDscores/13.l2.ldscore.gz'

CODE:
python mtag.py --sumstats EXP1MTAG.txt,EXP2MTAG.txt --ld_ref_panel /LDscores/ --out /EXP1EXP2MTAG/test6 --n_min 0 &

Do you have any suggestions as to what should I do to overcome this issue?

**Comment by rkwalters** [comment]
Hi,

There's a hard coded integer _N_CHR in the ldsc scripts allele_info.py and sumstats.py (located in ./ldsc_mod/ldscore/). You should be able to modify those values to 12 to resolve this error. (There's a few other mentions of 22 chromosomes in the code, but from a first look they don't appear consequential to your analysis.)

Cheers,
Raymond

**Comment by lcastanoduque0105** [comment]
Hi,

That worked!!!! :) 

Thanks,
Lina
