### ISSUE TITLE
Singular matrix

### ISSUE THREAD

**Issue by joellepasman** [omeed-maghzian/mtag#29]
I'm not very familiar with matrix calculations. The LDSC part of the script seems to run fine, but there are negatives in my sigma hat matrix and I get the error 'Singular matrix'. Would you know what might be the problem? This is my log file:

`
Calling ./mtag.py \
--n-min 0 \
--sumstats /home/jpasman/LDpred/MTG/sumstatsalc_clean,/home/jpasman/LDpred/MTG/sumstatscpd_clean,/home/jpasman/LDpred/MTG/sumstatscpd_clean \
--out ./cpdalccan 

2018/05/03/11:21:15 AM Beginning MTAG analysis...
2018/05/03/11:21:29 AM Read in Trait 1 summary statistics (9647583 SNPs) from /home/jpasman/LDpred/MTG/sumstatsalc_clean ...
2018/05/03/11:21:29 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:21:29 AM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/05/03/11:21:29 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:21:29 AM Interpreting column names as follows:
2018/05/03/11:21:29 AM snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

2018/05/03/11:21:30 AM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/05/03/11:21:44 AM Read 9647583 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
9647583 SNPs remain.
2018/05/03/11:21:51 AM Removed 0 SNPs with duplicated rs numbers (9647583 SNPs remain).
2018/05/03/11:21:52 AM Removed 0 SNPs with N < 74754.0 (9647583 SNPs remain).
2018/05/03/11:22:21 AM Median value of SIGNED_SUMSTATS was -0.0038335, which seems sensible.
2018/05/03/11:22:22 AM Dropping snps with null values
2018/05/03/11:22:23 AM 
Metadata:
2018/05/03/11:22:23 AM Mean chi^2 = 1.122
2018/05/03/11:22:23 AM Lambda GC = 1.101
2018/05/03/11:22:23 AM Max chi^2 = 132.526
2018/05/03/11:22:23 AM 414 Genome-wide significant SNPs (some may have been removed by filtering).
2018/05/03/11:22:23 AM 
Conversion finished at Thu May  3 11:22:23 2018
2018/05/03/11:22:23 AM Total time elapsed: 53.96s
2018/05/03/11:22:36 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:22:36 AM Munging of Trait 1 complete. SNPs remaining:	 9647583
2018/05/03/11:22:36 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/05/03/11:22:55 AM Read in Trait 2 summary statistics (2415427 SNPs) from /home/jpasman/LDpred/MTG/sumstatscpd_clean ...
2018/05/03/11:22:55 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:22:55 AM Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/05/03/11:22:55 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:22:55 AM Interpreting column names as follows:
2018/05/03/11:22:55 AM snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

2018/05/03/11:22:55 AM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/05/03/11:22:59 AM Read 2415427 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
2415427 SNPs remain.
2018/05/03/11:23:00 AM Removed 0 SNPs with duplicated rs numbers (2415427 SNPs remain).
2018/05/03/11:23:00 AM Removed 0 SNPs with N < 49368.6666667 (2415427 SNPs remain).
2018/05/03/11:23:08 AM Median value of SIGNED_SUMSTATS was 0.0244989, which seems sensible.
2018/05/03/11:23:08 AM Dropping snps with null values
2018/05/03/11:23:08 AM 
Metadata:
2018/05/03/11:23:08 AM Mean chi^2 = 1.051
2018/05/03/11:23:08 AM Lambda GC = 1.055
2018/05/03/11:23:08 AM Max chi^2 = 152.803
2018/05/03/11:23:08 AM 132 Genome-wide significant SNPs (some may have been removed by filtering).
2018/05/03/11:23:08 AM 
Conversion finished at Thu May  3 11:23:08 2018
2018/05/03/11:23:08 AM Total time elapsed: 12.8s
2018/05/03/11:23:11 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:23:11 AM Munging of Trait 2 complete. SNPs remaining:	 2415427
2018/05/03/11:23:11 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/05/03/11:23:18 AM Read in Trait 3 summary statistics (2415427 SNPs) from /home/jpasman/LDpred/MTG/sumstatscpd_clean ...
2018/05/03/11:23:18 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:23:18 AM Munging Trait 3  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/05/03/11:23:18 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:23:18 AM Interpreting column names as follows:
2018/05/03/11:23:18 AM snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

2018/05/03/11:23:18 AM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/05/03/11:23:21 AM Read 2415427 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
2415427 SNPs remain.
2018/05/03/11:23:22 AM Removed 0 SNPs with duplicated rs numbers (2415427 SNPs remain).
2018/05/03/11:23:23 AM Removed 0 SNPs with N < 49368.6666667 (2415427 SNPs remain).
2018/05/03/11:23:30 AM Median value of SIGNED_SUMSTATS was 0.0244989, which seems sensible.
2018/05/03/11:23:30 AM Dropping snps with null values
2018/05/03/11:23:30 AM 
Metadata:
2018/05/03/11:23:30 AM Mean chi^2 = 1.051
2018/05/03/11:23:30 AM Lambda GC = 1.055
2018/05/03/11:23:30 AM Max chi^2 = 152.803
2018/05/03/11:23:30 AM 132 Genome-wide significant SNPs (some may have been removed by filtering).
2018/05/03/11:23:30 AM 
Conversion finished at Thu May  3 11:23:30 2018
2018/05/03/11:23:30 AM Total time elapsed: 12.75s
2018/05/03/11:23:33 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/03/11:23:33 AM Munging of Trait 3 complete. SNPs remaining:	 2415427
2018/05/03/11:23:33 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/05/03/11:23:48 AM Trait 2 summary statistics: 	 2200165 SNPs remaining merging with previous traits.
2018/05/03/11:23:54 AM Trait 3 summary statistics: 	 2200165 SNPs remaining merging with previous traits.
2018/05/03/11:23:58 AM ... Merge of GWAS summary statistics complete. Number of SNPs:	 2200165
2018/05/03/11:24:01 AM Using 1863953 SNPs to estimate Omega (336212 SNPs excluded due to strand ambiguity)
2018/05/03/11:24:01 AM Estimating sigma..
2018/05/03/11:25:32 AM Checking for positive definiteness ..
2018/05/03/11:25:32 AM Sigma hat:
[[ 1.013 -0.003 -0.003]
 [-0.003  1.008  1.008]
 [-0.003  1.008  1.008]]
2018/05/03/11:25:32 AM Mean chi^2 of SNPs used to estimate Omega is low for some SNPsMTAG may not perform well in this situation.
2018/05/03/11:25:32 AM Beginning estimation of Omega ...
2018/05/03/11:25:32 AM Using GMM estimator of Omega ..
2018/05/03/11:25:32 AM Checking for positive definiteness ..
2018/05/03/11:25:32 AM Completed estimation of Omega ...
2018/05/03/11:25:32 AM Beginning MTAG calculations...
2018/05/03/11:25:41 AM Singular matrix
Traceback (most recent call last):
  File "/home/jpasman/LDpred/MTG/mtag/mtag.py", line 1348, in <module>
    mtag(args)
  File "/home/jpasman/LDpred/MTG/mtag/mtag.py", line 1242, in mtag
    mtag_betas, mtag_se = mtag_analysis(Zs, Ns, args.omega_hat, args.sigma_hat)
  File "/home/jpasman/LDpred/MTG/mtag/mtag.py", line 714, in mtag_analysis
    inv_xx = np.linalg.inv(xx)
  File "/sara/sw/python-2.7.9/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 513, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/sara/sw/python-2.7.9/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
LinAlgError: Singular matrix`

**Comment by paturley** [comment]
The problem is not the negative values of the Sigma matrix as much as the
fact that the (2,3) element of the matrix is identical to the (2,2) and the
(3,3) element of the matrix. Looks like you've maybe input the exact same
data for traits 2 and 3?

**Comment by joellepasman** [comment]
Yep, that was it, a simple syntax error. Thanks for the quick anser!
