### ISSUE TITLE
error running the example

### ISSUE THREAD

**Issue by jchung22** [omeed-maghzian/mtag#33]
Hello, 

I am using Anaconda: Python 2.7.13 |Anaconda 2.3.0 (64-bit)| (default, Dec 20 2016, 23:09:15) . 
I tried to run the MTAG example:
python ../mtag.py  --sumstats 1_OA2016_hm3samp_NEUR.txt,1_OA2016_hm3samp_SWB.txt  --out ./tutorial_results_1.1NS --n_min 0.0 --stream_stdout  &

But, I got an error message below:
...
2018/05/21/01:40:58 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/05/21/01:40:58 PM Munging of Trait 2 complete. SNPs remaining:      65374
2018/05/21/01:40:58 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/05/21/01:40:58 PM Trait 2 summary statistics:       20321 SNPs after merging with previous traits.
2018/05/21/01:40:58 PM ... Merge of GWAS summary statistics complete. Number of SNPs:    20321
2018/05/21/01:40:58 PM Using 20321 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
2018/05/21/01:40:58 PM Estimating sigma..
2018/05/21/01:41:18 PM Checking for positive definiteness ..
2018/05/21/01:41:18 PM Sigma hat:
[[ 1.043 -0.129]
 [-0.129  0.966]]
2018/05/21/01:41:18 PM Beginning estimation of Omega ...
2018/05/21/01:41:18 PM Using GMM estimator of Omega ..
2018/05/21/01:41:18 PM Checking for positive definiteness ..
2018/05/21/01:41:18 PM Completed estimation of Omega ...
2018/05/21/01:41:18 PM Beginning MTAG calculations...
2018/05/21/01:41:18 PM  ... Completed MTAG calculations.
2018/05/21/01:41:18 PM Writing Phenotype 1 to file ...
2018/05/21/01:41:18 PM Writing Phenotype 2 to file ...
2018/05/21/01:41:18 PM can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "../mtag.py", line 1359, in <module>
    mtag(args)
  File "../mtag.py", line 1249, in mtag
    save_mtag_results(args, res_temp,Zs,Ns, Fs,mtag_betas,mtag_se)
  File "../mtag.py", line 828, in save_mtag_results
    final_summary += str(summary_df.round(3))+'\n'
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.3.0-jupyter/lib/python2.7/site-packages/pandas/core/frame.py", line 4396, in round
    new_cols = [np.round(v, decimals) for _, v in self.iteritems()]
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.3.0-jupyter/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2793, in round_
    return round(decimals, out)

**Comment by huilisabrina** [comment]
Hi @jchung22 ,

This may be a package version problem. What's the version of `pandas` you're using? 

Thanks,
Hui

**Comment by jchung22** [comment]
Dear Hui,

Thank you for your reply.
I think the version of pandas that I am using was 0.17.1. FYI, I am using the Anaconda module in the Broad cluster (ie. use Anaconda).

Best,
Jaeyoon

**Comment by huilisabrina** [comment]
Hi @jchung22 ,

Thanks for checking. I tested using pandas 0.20.2 and it worked fine. Can you update `pandas` to 0.20.2 and rerun to see if that solves the problem? 

Best,
Hui

**Comment by jchung22** [comment]
Thanks!

Jaeyoon
