### ISSUE TITLE
If freq is not available,

### ISSUE THREAD

**Issue by jchung22** [omeed-maghzian/mtag#34]
Hello,

I wonder if I can use MTAG for a gwas summary which do not have freq information. I downloaded GWAS summary data sets, and one of them do not have freq information. 
Also, do you expect this frequency of a SNP computed from only controls, only cases, or both?

Best,
Jaeyoon

**Comment by paturley** [comment]
Hi Jaeyoon,

If you have a good reference panel, it is likely just fine to add your own column with frequency information. I think the only time the freq gets used in in QC at the beginning and when the z-scores are transformed into betas and SE at the end. ( @huilisabrina should correct me if I'm wrong though.)

It's probably best to use the frequency in both cases and controls if it's available, but unless the trait you are looking at is nearly Mendelian, I don't think it should matter much.

Best,
Patrick

**Comment by jchung22** [comment]
Thank you!

Best,
Jaeyoon
