### ISSUE TITLE
ValueError: You are trying to merge on object and float64 columns

### ISSUE THREAD

**Issue by cks2903** [omeed-maghzian/mtag#38]
When trying to run the MTAG analysis on my data, I get the following error message.
**ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat** 

I have no idea how to fix this problem. The input files are both in the format specified in tutorial 1.

The log file:

2018/08/13/10:15:19 AM 
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<>
<> MTAG: Multi-trait Analysis of GWAS 
<> Version: 1.0.8
<> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
<> Harvard University Department of Economics / Broad Institute of MIT and Harvard
<> GNU General Public License v3
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<> Note:  It is recommended to run your own QC on the input before using this program. 
<> Software-related correspondence: maghzian@nber.org 
<> All other correspondence: paturley@broadinstitute.org 
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Calling ./mtag.py \
--stream-stdout  \
--n-min 0.0 \
--sumstats OW_Rate-2year.txt,OWrate2016MGATformat.txt \
--out ./output 

2018/08/13/10:15:19 AM Beginning MTAG analysis...
2018/08/13/10:15:19 AM Read in Trait 1 summary statistics (201694 SNPs) from OW_Rate-2year.txt ...
2018/08/13/10:15:19 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:19 AM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/08/13/10:15:19 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:19 AM Interpreting column names as follows:
2018/08/13/10:15:19 AM snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

2018/08/13/10:15:19 AM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/08/13/10:15:20 AM Read 201694 SNPs from --sumstats file.
Removed 299 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
201395 SNPs remain.
2018/08/13/10:15:20 AM Removed 0 SNPs with duplicated rs numbers (201395 SNPs remain).
2018/08/13/10:15:20 AM Removed 0 SNPs with N < 172.0 (201395 SNPs remain).
2018/08/13/10:15:21 AM Median value of SIGNED_SUMSTATS was 0.063935831, which seems sensible.
2018/08/13/10:15:21 AM Dropping snps with null values
2018/08/13/10:15:21 AM 
Metadata:
2018/08/13/10:15:21 AM Mean chi^2 = 1.057
2018/08/13/10:15:21 AM Lambda GC = 0.986
2018/08/13/10:15:21 AM Max chi^2 = 21.611
2018/08/13/10:15:21 AM 0 Genome-wide significant SNPs (some may have been removed by filtering).
2018/08/13/10:15:21 AM 
Conversion finished at Mon Aug 13 10:15:21 2018
2018/08/13/10:15:21 AM Total time elapsed: 2.18s
2018/08/13/10:15:21 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:21 AM Munging of Trait 1 complete. SNPs remaining:	 201395
2018/08/13/10:15:21 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/08/13/10:15:22 AM Read in Trait 2 summary statistics (201694 SNPs) from OWrate2016MGATformat.txt ...
2018/08/13/10:15:22 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:22 AM Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2018/08/13/10:15:22 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:22 AM Interpreting column names as follows:
2018/08/13/10:15:22 AM snpid:	Variant ID (e.g., rs number)
n:	Sample size
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
z:	Directional summary statistic as specified by --signed-sumstats.

2018/08/13/10:15:22 AM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2018/08/13/10:15:22 AM Read 201694 SNPs from --sumstats file.
Removed 242 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
201452 SNPs remain.
2018/08/13/10:15:23 AM Removed 0 SNPs with duplicated rs numbers (201452 SNPs remain).
2018/08/13/10:15:23 AM Removed 0 SNPs with N < 172.0 (201452 SNPs remain).
2018/08/13/10:15:24 AM Median value of SIGNED_SUMSTATS was 0.0337629845, which seems sensible.
2018/08/13/10:15:24 AM Dropping snps with null values
2018/08/13/10:15:24 AM 
Metadata:
2018/08/13/10:15:24 AM Mean chi^2 = 1.076
2018/08/13/10:15:24 AM Lambda GC = 0.998
2018/08/13/10:15:24 AM Max chi^2 = 22.221
2018/08/13/10:15:24 AM 0 Genome-wide significant SNPs (some may have been removed by filtering).
2018/08/13/10:15:24 AM 
Conversion finished at Mon Aug 13 10:15:24 2018
2018/08/13/10:15:24 AM Total time elapsed: 1.88s
2018/08/13/10:15:24 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2018/08/13/10:15:24 AM Munging of Trait 2 complete. SNPs remaining:	 201452
2018/08/13/10:15:24 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2018/08/13/10:15:25 AM Dropped 0 SNPs due to strand ambiguity, 201395 SNPs remain in intersection after merging trait1
2018/08/13/10:15:25 AM Dropped 0 SNPs due to strand ambiguity, 201395 SNPs remain in intersection after merging trait2
2018/08/13/10:15:25 AM ... Merge of GWAS summary statistics complete. Number of SNPs:	 201395
2018/08/13/10:15:26 AM Using 201395 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
2018/08/13/10:15:26 AM Estimating sigma..
2018/08/13/10:15:34 AM You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat
Traceback (most recent call last):
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/mtag.py", line 1514, in <module>
    mtag(args)
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/mtag.py", line 1287, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/mtag.py", line 417, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/ldsc_mod/ldscore/sumstats.py", line 423, in estimate_rg
    M_annot, w_ld_cname, ref_ld_cnames, sumstats, _ = _read_ld_sumstats(args, log, None, alleles=True, dropna=True,sumstats=p1)
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/ldsc_mod/ldscore/sumstats.py", line 251, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/ldsc_mod/ldscore/sumstats.py", line 233, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/Users/CathrineKiel/Desktop/MTAG/mtag/ldsc_mod/ldscore/sumstats.py", line 77, in smart_merge
    out = pd.merge(x, y, how='inner', on='SNP')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 61, in merge
    validate=validate)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 555, in __init__
    self._maybe_coerce_merge_keys()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/reshape/merge.py", line 986, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat
2018/08/13/10:15:35 AM Analysis terminated from error at Mon Aug 13 10:15:35 2018
2018/08/13/10:15:35 AM Total time elapsed: 15.85s

**Comment by paturley** [comment]
Hmm. It looks as if there may be a type mismatch. Are you sure that all the values in your data are numeric?

**Comment by cks2903** [comment]
The only values in my data that are not numeric are the ones in the a1 and a2 columns. Also my data includes NA on 199 SNPs with missing values, but the log-file indicates that the analysis recognize these and remove them..

**Comment by cks2903** [comment]
I changed my snpids to be called "rs1","rs2" etc. instead of "1", "2"... That solved them problem.

**Comment by paturley** [comment]
Glad you got this to work!
