### ISSUE TITLE
tutorial not working,  SE requested but not in example files

### ISSUE THREAD

**Issue by ukuvainik** [omeed-maghzian/mtag#43]
Hi
I am trying to run the tutorial, but the program seems to be expecting a SE column, which should not be necessary

[tutorial_results_1.1NS.log](https://github.com/omeed-maghzian/mtag/files/2379627/tutorial_results_1.1NS.log)

Best,

Uku

**Comment by huilisabrina** [comment]
Hey @ukuvainik 

Thanks! Indeed SE shouldn't be required at that step. I've fixed this. Please re-pull the repository and try again.

Best,
Hui

**Comment by ukuvainik** [comment]
Hi,

Thanks for the quick fix.  I do not get a SE error any more, but now it asks for a frequency column?

[tutorial_results_1.1NS.log](https://github.com/omeed-maghzian/mtag/files/2379747/tutorial_results_1.1NS.log)

**Comment by huilisabrina** [comment]
@ukuvainik Yes the allele frequency column is required in MTAG. Please see our wiki page [here](https://github.com/omeed-maghzian/mtag/wiki/Tutorial-1:-The-Basics#sample-gwas-results-and-data-format) on description of the required GWAS input format. `freq` is used to filter rare variants and weight convert MTAG results to unstandardized effect sizes.

**Comment by ukuvainik** [comment]
of course, @huilisabrina 
I am using the tutorial files, which already have that with "freq" name.

I tried manually setting 	--eaf_name freq \ , but it does not change things and does not even reflect in the log.

[tutorial_results_1.1NS.log](https://github.com/omeed-maghzian/mtag/files/2379815/tutorial_results_1.1NS.log)

**Comment by huilisabrina** [comment]
@ukuvainik I see what the problem is. Will try to fix that asap! Thanks again for raising this.

**Comment by huilisabrina** [comment]
Hi @ukuvainik ,

I just fixed this issue. Please feel free to try again and let me know if you have any further questions! 

Thanks,
Hui

**Comment by ukuvainik** [comment]
thank you @huilisabrina , the tutorial is now working!
