### ISSUE TITLE
ValueError : Could not determine N with --use-beta-se parameter

### ISSUE THREAD

**Issue by MOohTus** [omeed-maghzian/mtag#46]
Hi, 

I saw that recently, MTAG takes BETA and SE instead of Z-score and N. 
So I used `--use_beta_se` `--beta_name` and `--se_name` but, I have an error : 

> MTAG could not determine N

 
Should I give the N column with BETA and SE anyway ? 
Also when I used `--use_beta_se` only (with my column named beta and se) I have an other error : 

> Could not find SIGNED_SUMSTAT column

Thank you !

Morgane

There is my log file for the first question :

> 2018/10/25/10:44:02 AM 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <>
> <> MTAG: Multi-trait Analysis of GWAS 
> <> Version: 1.0.8
> <> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
> <> Harvard University Department of Economics / Broad Institute of MIT and Harvard
> <> GNU General Public License v3
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <> Note:  It is recommended to run your own QC on the input before using this program. 
> <> Software-related correspondence: maghzian@nber.org 
> <> All other correspondence: paturley@broadinstitute.org 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 
> 
> Calling ./mtag.py \
> --se-name SE \
> --n-min 0.0 \
> --ld-ref-panel ldscore_calc/filtered-set_test2_mis84maf3_bgl_ref_ldscores/filtered-set_test2_mis84ma
> f3_bgl_withNames_newCHRNames_ \
> --use-beta-se  \
> --sumstats 1DmeansTS_06182.assoc.4MVP,1DmeansTS_06186.assoc.4MVP,1DmeansTS_061811.assoc.4MVP \
> --beta-name BETA \
> --out ./CompoProt_T_MTAG 
> 
> 2018/10/25/10:44:02 AM Beginning MTAG analysis...
> 2018/10/25/10:44:02 AM MTAG will use the provided BETA/SE columns for analyses.
> 2018/10/25/10:44:20 AM Read in Trait 1 summary statistics (5591340 SNPs) from 1DmeansTS_06182.assoc.4MVP ...
> 2018/10/25/10:44:20 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 2018/10/25/10:44:20 AM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
> 2018/10/25/10:44:20 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 2018/10/25/10:44:20 AM 
> ERROR converting summary statistics:
> 
> 2018/10/25/10:44:20 AM Traceback (most recent call last):
>   File "MTAG/mtag-master_Octobre18/mtag_munge.py", line 812, in munge_sumstats
>     raise ValueError('Could not determine N.')
> ValueError: Could not determine N.
> 
> 2018/10/25/10:44:20 AM 
> Conversion finished at Thu Oct 25 10:44:20 2018
> 2018/10/25/10:44:20 AM Total time elapsed: 0.0s
> 2018/10/25/10:44:20 AM Could not determine N.
> Traceback (most recent call last):
>   File "../mtag-master_Octobre18/mtag.py", line 1520, in <module>
>     mtag(args)
>   File "../mtag-master_Octobre18/mtag.py", line 1291, in mtag
>     DATA_U, DATA, args = load_and_merge_data(args)
>   File "../mtag-master_Octobre18/mtag.py", line 245, in load_and_merge_data
>     GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
>   File "../mtag-master_Octobre18/mtag.py", line 159, in _perform_munge
>     munged_results = munge_sumstats.munge_sumstats(argnames, write_out=False, new_log=False)
>   File "MTAG/mtag-master_Octobre18/mtag_munge.py", line 812, in munge_sumstats
>     raise ValueError('Could not determine N.')
> ValueError: Could not determine N.
> 2018/10/25/10:44:20 AM Analysis terminated from error at Thu Oct 25 10:44:20 2018
> 2018/10/25/10:44:20 AM Total time elapsed: 18.19s

There is my log file for the second question :

> 2018/10/25/10:19:29 AM 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <>
> <> MTAG: Multi-trait Analysis of GWAS 
> <> Version: 1.0.8
> <> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
> <> Harvard University Department of Economics / Broad Institute of MIT and Harvard
> <> GNU General Public License v3
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <> Note:  It is recommended to run your own QC on the input before using this program. 
> <> Software-related correspondence: maghzian@nber.org 
> <> All other correspondence: paturley@broadinstitute.org 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 
> 
> Calling ./mtag.py \
> --se-name s \
> --ld-ref-panel MTAG/Medicago_PMG/ldscore_calc/filtered-set_test2_mis84maf3_bgl_ref_ldscores/filtered-set_test2_mis84maf3_bgl_withNames_newCHRNames_ \
> --use-beta-se  \
> --sumstats 1DmeansTS_06182.assoc.4MVP,1DmeansTS_06186.assoc.4MVP,1DmeansTS_061811.assoc.4MVP \
> --beta-name b \
> --out ./CompoProt_T_MTAG 
> 
> 2018/10/25/10:19:29 AM Beginning MTAG analysis...
> 2018/10/25/10:19:29 AM MTAG will use the provided BETA/SE columns for analyses.
> 2018/10/25/10:19:47 AM Read in Trait 1 summary statistics (5591340 SNPs) from 1DmeansTS_06182.assoc.4MVP ...
> 2018/10/25/10:19:47 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 2018/10/25/10:19:47 AM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
> 2018/10/25/10:19:47 AM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 2018/10/25/10:19:47 AM 
> ERROR converting summary statistics:
> 
> 2018/10/25/10:19:47 AM Traceback (most recent call last):
>   File "MTAG/mtag-master_Octobre18/mtag_munge.py", line 796, in munge_sumstats
>     raise ValueError('Could not find {C} column.'.format(C=c))
> ValueError: Could not find SIGNED_SUMSTAT column.
> 
> 2018/10/25/10:19:47 AM 
> Conversion finished at Thu Oct 25 10:19:47 2018
> 2018/10/25/10:19:47 AM Total time elapsed: 0.0s
> 2018/10/25/10:19:47 AM Could not find SIGNED_SUMSTAT column.
> Traceback (most recent call last):
>   File "../mtag-master_Octobre18/mtag.py", line 1520, in <module>
>     mtag(args)
>   File "../mtag-master_Octobre18/mtag.py", line 1291, in mtag
>     DATA_U, DATA, args = load_and_merge_data(args)
>   File "../mtag-master_Octobre18/mtag.py", line 245, in load_and_merge_data
>     GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
>   File "../mtag-master_Octobre18/mtag.py", line 159, in _perform_munge
>     munged_results = munge_sumstats.munge_sumstats(argnames, write_out=False, new_log=False)
>   File "MTAG/mtag-master_Octobre18/mtag_munge.py", line 796, in munge_sumstats
>     raise ValueError('Could not find {C} column.'.format(C=c))
> ValueError: Could not find SIGNED_SUMSTAT column.
> 2018/10/25/10:19:47 AM Analysis terminated from error at Thu Oct 25 10:19:47 2018
> 2018/10/25/10:19:47 AM Total time elapsed: 18.25s

**Comment by huilisabrina** [comment]
Hi,

Thanks for raising these questions. Yes the N column is necessary even in the Beta/Se mode. It’s used both for weighting the Z scores to get the unstandardized effect size, and for basic filtering of the SNPs. The second question is odd, but I’ll get back to it ASAP. 

Best,
Hui

**Comment by huilisabrina** [comment]
Hi @MOohTus ,

Do all three input sumstats share the same colnames, in particular those that you specified (i.e. `b` and `s`)? I did a quick test but couldn't replicate the issue you had. 

Thanks,
Hui

**Comment by MOohTus** [comment]
Hi, 

Thank you for your answer. 

I re-pulled and tried again and I find a new error : 

> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

When I specified the columns names and names are different of beta and se, it's working.

Thank you, 

Morgane

There is my log file, I specified my columns names `--beta_name` beta and `--se_name` se: 

> 2018/10/29/03:53:52 PM 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <>
> <> MTAG: Multi-trait Analysis of GWAS 
> <> Version: 1.0.8
> <> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
> <> Harvard University Department of Economics / Broad Institute of MIT and Harvard
> <> GNU General Public License v3
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> <> Note:  It is recommended to run your own QC on the input before using this program. 
> <> Software-related correspondence: maghzian@nber.org 
> <> All other correspondence: paturley@broadinstitute.org 
> <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> 
> 
> Calling ./mtag.py \
> --n-min 0.0 \
> --ld-ref-panel /MTAG/Medicago_PMG/ldscore_calc/filtered-set_test2_mis84maf3_bgl_ref_ldscores/filtered-set_test2_mis84maf3_bgl_withNames_newCHRNames_ \
> --use-beta-se  \
> --sumstats test_1_cov_RI.LMM.assoc_BETA.MTAG_min,test_1_cov_BN.LMM.assoc_BETA.MTAG_min \
> --out ./PMG_RI_BN_Oct18_MTAG_BETA_v2 
> 
> 2018/10/29/03:53:52 PM Beginning MTAG analysis...
> 2018/10/29/03:53:52 PM MTAG will use the provided BETA/SE columns for analyses.
> 2018/10/29/03:54:12 PM Read in Trait 1 summary statistics (5590385 SNPs) from test_1_cov_RI.LMM.assoc_BETA.MTAG_min ...
> 2018/10/29/03:54:12 PM unsupported operand type(s) for +: 'NoneType' and 'str'
> Traceback (most recent call last):
>   File "../../mtag-master_Octobre18_v2/mtag.py", line 1533, in <module>
>     mtag(args)
>   File "../../mtag-master_Octobre18_v2/mtag.py", line 1304, in mtag
>     DATA_U, DATA, args = load_and_merge_data(args)
>   File "../../mtag-master_Octobre18_v2/mtag.py", line 257, in load_and_merge_data
>     GWAS_d[p], sumstats_format[p] = _perform_munge(args, GWAS_d[p], gwas_dat_gen, p)
>   File "../../mtag-master_Octobre18_v2/mtag.py", line 151, in _perform_munge
>     argnames = Namespace(sumstats=None,N=None,N_cas=None,N_con=None,out=out,maf_min=args.maf_min_list[p], info_min =args.info_min_list[p],daner=False, no_alleles=False, merge_alleles=merge_alleles,n_min=a
> rgs.n_min_list[p],chunksize=args.chunksize, snp=args.snp_name,N_col=args.n_name, N_cas_col=None, N_con_col = None, a1=a1_munge, a2=a2_munge, p=None,frq=eaf_munge,signed_sumstats=beta_munge+',0', keep_beta
> =True, keep_se=True, info=None,info_list=None, nstudy=None,nstudy_min=None,ignore=ignore_list,a1_inc=False, keep_maf=True, daner_n=False, keep_str_ambig=True, input_datgen=GWAS_dat_gen, cnames=list(origin
> al_cols))
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> 2018/10/29/03:54:12 PM Analysis terminated from error at Mon Oct 29 15:54:12 2018
> 2018/10/29/03:54:12 PM Total time elapsed: 20.01s

**Comment by huilisabrina** [comment]
Hi @MOohTus , 
Sorry for the back and forth. I fixed two more lines and now it should be applicable to more general cases. If your problems are cleared, feel free to close the issue. 
Thanks!
Hui

**Comment by MOohTus** [comment]
Hi, 

It's working ! Thank you !

Morgane
