### ISSUE TITLE
cannot multiply sequence by non-int of type float

### ISSUE THREAD

**Issue by andgan** [omeed-maghzian/mtag#5]
Running MTAG with this command line:

```
Calling ./mtag.py \
--z-name Z \
--bpos-name BP \
--verbose  \
--stream-stdout  \
--n-name N \
--a2-name ALLELE0 \
--n-min 0 \
--a1-name ALLELE1 \
--snp-name SNP \
--chr-name CHR \
--sumstats temp,temp2 \
--out out
```
But get the error below, bit files however get generated. Log is also attached.

```
Writing Phenotype 1 to file ...
Writing Phenotype 2 to file ...
can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/wip/aganna/mtag-master/mtag.py", line 1382, in <module>
    mtag(args)
  File "/humgen/atgu1/fs03/wip/aganna/mtag-master/mtag.py", line 1279, in mtag
    save_mtag_results(args, res_temp,Zs,Ns, Fs,mtag_betas,mtag_se)
  File "/humgen/atgu1/fs03/wip/aganna/mtag-master/mtag.py", line 840, in save_mtag_results
    final_summary += str(summary_df.round(3))+'\n'
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.3.0-jupyter/lib/python2.7/site-packages/pandas/core/frame.py", line 4396, in round
    new_cols = [np.round(v, decimals) for _, v in self.iteritems()]
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.3.0-jupyter/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2793, in round_
    return round(decimals, out)
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.3.0-jupyter/lib/python2.7/site-packages/pandas/core/series.py", line 1240, in round
    result = _values_from_object(self).round(decimals, out=out)
TypeError: can't multiply sequence by non-int of type 'float'
Analysis terminated from error at Sat Nov 18 13:41:26 2017

```

[mixmodel_mainpheno_klein_sexual_partners_qt_M_mtag.log](https://github.com/omeed-maghzian/mtag/files/1484928/mixmodel_mainpheno_klein_sexual_partners_qt_M_mtag.log)

**Comment by omeed-maghzian** [comment]
Just to clarify: bad summary statistics in the input file would be a possible source of this error as well as the incredibly high p-value you get from the other issue you posted (#6).

**Comment by andgan** [comment]
So, yes there are some NaN in the input file for the Z statistic, I’m trying to remove and re-run MTAG, Will keep you posted with the results.
Cheers,

**Comment by andgan** [comment]
Hi,
I get the same error even after removing the NaN.
Cheers,

**Comment by omeed-maghzian** [comment]
Did you attempt to replace the NaN Z-scores with another number or did you remove them completely? How about N?

**Comment by andgan** [comment]
I removed them completely N is fine, no missing or NaN

**Comment by andgan** [comment]
And there are no missing or Nan in the output file.

**Comment by andgan** [comment]
I can share with you the files if you have access to broad cluster or orchestra.
Cheers,

**Comment by paturley** [comment]
I should have access to the Broad cluster. Am I allowed to transfer the
files to where Omeed can access them?

**Comment by andgan** [comment]
Hi,
Sure here is the link to the two files:
/humgen/atgu1/fs03/wip/aganna/uk_bio/SSI/GWAS/final_st/temp
/humgen/atgu1/fs03/wip/aganna/uk_bio/SSI/GWAS/final_st/temp2

Cheers,

**Comment by andgan** [comment]
Hi Omeed,
Any update on this? Is there something I can help with?
Thanks
Cheers,

**Comment by paturley** [comment]
It's my fault. I need to transfer the data still. I'll do it now.

**Comment by andgan** [comment]
Thanks!

**Comment by paturley** [comment]
I've transferred the files.

**Comment by omeed-maghzian** [comment]
Hi @andgan , I wasn't able to replicate the error you got given your provided command. 
 
This is mtag call I used, from the same folder as the sumstats (replace `${mtag}` with the location of `mtag.py`:
```
python ${mtag} \
	--z_name Z \
	--bpos_name BP \
	--verbose  \
	--stream_stdout \
	--n_name N \
	--n_min 0 \
	--snp_name SNP \
	--chr_name CHR \
	--sumstats ./temp,./temp2 \
	--out ./out

```
The log file is [here](https://github.com/omeed-maghzian/mtag/files/1511076/out.log).

I would suggest the following:

* Update your copy of MTAG
* Check to make sure you are using `pandas v.0.18.1` and `numpy v.1.13.1` (or later)
* Run the above command and see if you get the same error.

Let me know if that works for you. 

Thanks,
Omeed

**Comment by andgan** [comment]
Hi, thanks!
I upgraded the pandas and numpy version and I can confirm that now it works, there is no error message, so that problem is solved.

However, I still have puzzling results:
If you check the top SNP, rs4408327 (you might have a different one), it has an MTAG P-value of 6.47188071544e-09, however it is not significant in any of the two files, how is that possible?

Cheers,

**Comment by paturley** [comment]
I'm confused why this is puzzling. If the SNP is marginally significant in
both files and in the same direction, then MTAG will use the fact that
these estimates are consistent to infer that there is actually an effect
there.

**Comment by andgan** [comment]
Hi,
See attached file, I think in this case it seems to pick up a completely different SNP (although they have the same name), the AF reported is different. 
Do you agree that this should not be possible?
I double checked my code, I cannot find obvious errors, but maybe I messed up something.

Cheers,

**Comment by paturley** [comment]
I don't see an attached file. I'm a bit confused. Is the problem that you have two SNPs that have the same name in each of your two input files, but you think they are different SNPs because of the MAF?

**Comment by andgan** [comment]
I attached the file to the email, but the file format apparently is not supported by github, so I made a file as .zip and attached now. I think that by looking at the file you should see what I mean, it seems that something is wrong with the way the SNP is processed.The AF is off as compared to the two input files, and the P-value does not seem possible to me.

[test.zip](https://github.com/omeed-maghzian/mtag/files/1512513/test.zip)

**Comment by omeed-maghzian** [comment]
Got it, I am seeing the same problem using the data I have been provided. What I suspect is happening is that the SNP information for the mtag output being printed is misaligned with the summary statistics (Z, Z_mtag, etc.). I'll explore this a bit more. Let's continue this conversation in #6 , as the issue listed here has been fixed.
