### ISSUE TITLE
Any issues with composite traits (e.g., weight, height^2, BMI)?

### ISSUE THREAD

**Issue by carbocation** [omeed-maghzian/mtag#50]
I know that in the supplement to the paper, you conducted an analysis on anthropometric traits, including BMI, weight, and waist-to-hip ratio. I wonder whether there would be any potential issue if you instead had done this with BMI, weight, and (say) height^2. 

I ask this since BMI is a synthetic trait that is entirely derived from weight and height^2 -- would analyzing all 3 together violate any assumptions of the algorithm?

**Comment by paturley** [comment]
Hey James,

I can't think of why doing something like this would cause MTAG to break
down. It may be that the composite trait was a linear combination of the
two other traits and the were all estimated in the exact same sample, it
would not give you additional information, but I can't think of how it
would violate any assumptions of the model or cause the code to fail. Have
you run into problems doing this?

Patrick

**Comment by carbocation** [comment]
Patrick - Thanks for your reply. I haven't seen anything concerning -- things actually look good, so the pessimist in me wondered whether such linear transformations were prima facie in violation of an assumption.

- James
