### ISSUE TITLE
INFO filtering without an INFO field

### ISSUE THREAD

**Issue by carbocation** [omeed-maghzian/mtag#51]
Just bumped into this, but it seems that if someone attempts to filter on INFO, but they have not provided MTAG with an INFO column, this should error out rather than "successfully" removing 0 SNPs.

**Comment by huilisabrina** [comment]
@carbocation I see what you're saying. Thanks for catching this! I've added inconsistency checks to not only INFO, but also MAF and N columns. Feel free to try again and let me know if you have any other questions!

**Comment by carbocation** [comment]
Thanks, @huilisabrina !
