### ISSUE TITLE
Using maf_min to preserve low-MAF SNPs without affecting the model

### ISSUE THREAD

**Issue by carbocation** [omeed-maghzian/mtag#58]
Looking at @andgan 's recent thread in which maf_min is set to 0, I am wondering to what extent that maf_min affects the MTAG omega estimation. If MTAG uses MAF 0.01 as a hard minimum for estimation, then I'd like to set maf_min to 0 to observe the re-weighted output. But if dropping maf_min to 0 will cause a change in how the omega and other matrices are computed, then I'd rather leave it untouched, even if that means that the low frequency spectrum SNPs cannot be output.

**Comment by andgan** [comment]
Actually that flag is redundant in my case, because I pre-filtered SNPs to freq 0.01. But it is a good question.
Cheers,

**Comment by carbocation** [comment]
It does seem that my output is slightly affected, but it's not clear that it's problematic (and I regain my low frequency SNPs). My QC approach pre-filters to keep the minor allele count > 100, and I see in the supplement that the authors pre-filtered to MAC > 30, so perhaps this should be well behaved. Still, a bit unclear from the paper (to me) whether the MAF of 0.01 that the software defaults to is important.

**Comment by carbocation** [comment]
Thanks Patrick. Empirically I didn't see much of a change in omega or sigma after changing my MAF in this particular instance (my MAC is still > 100 here, and I suspect that may be why I am seeing consistent behavior). Closing this issue.
