### ISSUE TITLE
Likely wrong results from MTAG

### ISSUE THREAD

**Issue by andgan** [omeed-maghzian/mtag#6]
Hi,

I'm running MTAG similarly to what indicated in the bug report `cannot multiply sequence by non-int of type float` (and get the same error). Moreover, the results look likely wrong. For example, top-SNP in the MTAG file is:

```
SNP              CHR       BP     a1 a2        Z            N           freq       mtag_beta 
rs11229352  11 58075672  G  A 4.967528 188669 0.681504 0.01696269 
 mtag_se         mtag_z        mtag_pval
0.002922755 5.803663 6.488153e-09
```

However the same SNP in the two summary statistic files read by MTAG has P-value: 0.58 and 0.12, so I don't see how it can get a P-value of 6.488153e-09 when MTAGed.

thanks

**Comment by omeed-maghzian** [comment]
Hi @andgan, 

Can you attach the full mtag log file that is produced? I'll look into fixes for #4 #5 and this on Monday.

Omeed

**Comment by andgan** [comment]
sure, thanks!
[mixmodel_mainpheno_klein_sexual_partners_qt_M_mtag.log](https://github.com/omeed-maghzian/mtag/files/1485054/mixmodel_mainpheno_klein_sexual_partners_qt_M_mtag.log)

**Comment by omeed-maghzian** [comment]
@andgan continuing the conversation from #5: one thing that I noticed is that the `SNP` column does not seem to be a unique identifier for `temp`. This may interfere with the mapping of the summary statistics across traits. Can you try rerunning MTAG with unique ids in the `SNP` column and see if you still get this problem? This is a necessary step in preparing sumstats for MTAG anyway.

**Comment by andgan** [comment]
Hi, sorry for the late reply. I removed duplicated SNPs from temp but I see the same behavior.
Any other suggestion?
Cheers,

**Comment by rkwalters** [comment]
Hi Andrea,
Seems like it would be helpful to get a more direct look at what happening in the munge and merge steps. 

Omeed, is --verbose sufficient to get those files and/or output the logging.debug() check of GWAS_all at line 271?

Cheers,
Raymond

**Comment by andgan** [comment]
Ok, let me know what I have to do. 
Cheers,

**Comment by andgan** [comment]
Hi omeed,
Is there any update on this? Let me know if I can help in any way.
Cheers,

**Comment by paturley** [comment]
Omeed is facing a couple grad school application deadlines today, but I
think he is working on it with the help of some other RAs. This is pretty
high on our priority list since, if the current version of MTAG is
producing junk results, we'd need to resolve that quickly.

**Comment by andgan** [comment]
Thanks for the update!

**Comment by omeed-maghzian** [comment]
Hi @andgan, thank you again for reporting this error, it was incredibly important to correct it. The problem came from to a minor misalignment when writing the results file. The most recent update to the code fixes this bug. Please pull the new version of MTAG and let me know if it works.

**Comment by andgan** [comment]
Hi omeed, I re-run the analysis and the results make sense now. Thanks for fixing this!!
Cheers,

**Comment by omeed-maghzian** [comment]
No problem, sorry it took so long!
