### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by curranth** [omeed-maghzian/mtag#64]
Hi there, 

I have been trying to run mtag, and unfortunately it has failed, throwing the error "too many values to unpack". Is this because there are too many SNPS? If so what is the limit and is there a way around this?

Thanks!

**Comment by paturley** [comment]
Hello. Can you attach or cut and paste the link file? That will help us
diagnose the problem.

Thanks!

**Comment by curranth** [comment]
This is the point at which it fails:

2019/03/19/10:54:42 AM Beginning estimation of Omega ...
2019/03/19/10:54:44 AM Using GMM estimator of Omega ..
2019/03/19/10:54:49 AM Checking for positive definiteness ..
2019/03/19/10:54:49 AM matrix is not positive definite, performing adjustment..
2019/03/19/10:54:49 AM Completed in 8 iterations
2019/03/19/10:54:49 AM Completed estimation of Omega ...
2019/03/19/10:56:53 AM There are 8600201 SNPs present in Traits [0 1 2]
2019/03/19/10:57:45 AM too many values to unpack
Traceback (most recent call last):
  File "./mtag.py", line 1557, in <module>
    mtag(args)
  File "./mtag.py", line 1401, in mtag
    Zs, Ns, Fs, resid_cols, _ = extract_gwas_sumstats(snp_df, args, tl)
ValueError: too many values to unpack
2019/03/19/10:57:45 AM Analysis terminated from error at Tue Mar 19 10:57:45 2019
2019/03/19/10:57:45 AM Total time elapsed: 40.0m:18.67s

Let me know if I can give you more info!

**Comment by huilisabrina** [comment]
Hi @curranth ,

Thank you for raising this issue. The information you gave was sufficient and it actually uncovers a bug in the codes. I have fixed it just now. Could you please re-pull the repo and try calling mtag again (with the `--meta_format` flag on)? Please let me know if you still have issues. 

Best,
Hui

**Comment by curranth** [comment]
Yep it seems to have worked! Thank you for your help!

**Comment by huilisabrina** [comment]
Great! I'm going to close this issue for now. Feel free to re-open it if you have any other questions. 

Best,
Hui
