### ISSUE TITLE
Can I include both binary and quantitative traits in the same MTAG run

### ISSUE THREAD

**Issue by phuwanat** [omeed-maghzian/mtag#66]
Hello,

Can I include both binary and quantitative traits in the same MTAG run? For example, running MTAG on GWAS of coronary artery disease and blood lipids. Thank you!

**Comment by paturley** [comment]
Yes, that should be fine as long as you use the beta coefficients from
summary statistics for the binary trait (as opposed to using the odds
ratios).

**Comment by phuwanat** [comment]
Great! This is reassuring.
Thank you very much.
