### ISSUE TITLE
crossover SNP are not shown in the results

### ISSUE THREAD

**Issue by YaoXueming** [omeed-maghzian/mtag#68]
hi，there
 
I used the MTAG to do meta-analysis with five cohort，and the result seems wrong. I wonder whether the most significant SNP in trait 5 is showing in the results, but when  egrep the SNP,   I did not find  the snp. 

[jli01@ln3%tianhe ASD]$ sort -g -k 9,9 iPSYCH-PGC_ASD_Nov2017 | head
CHR     SNP     BP      A1      A2      INFO    OR      SE      P
20      rs910805        21248116        A       G       0.999   0.90874 0.016   2.041e-09
20      rs1000177       21233198        T       C       0.996   1.10142 0.0163  3.323e-09'
[jli01@ln3%tianhe mtag-master]$ egrep -w "rs910805" all-mtag-2_trait_5_asd.txt
[jli01@ln3%tianhe mtag-master]$

I thought maybe because other traits don't have it separately and I egrep the SNP in other traits, and it shows the snp is crossover. So I want to know the filter condition of this software or some suggestion.

[jli01@ln3%tianhe ADHD]$ egrep -w "rs910805" European-Ancestry-GWAS
20      rs910805        21248116        A       G       0.994   0.94554 0.0156  0.0003314
[jli01@ln3%tianhe cell]$ egrep -w "rs910805" BDvsCONT.sumstats
20      rs910805        21248116        A       G       0.767   0.768   0.991   0.99164 0.0175  0.6291  -+--++--+-++---+-++-----+--+-++-0.943
[jli01@ln3%tianhe cell]$ egrep -w "rs910805" SCZvsCONT.sumstats
20      rs910805        21248116        A       G       0.762   0.771   0.997   0.95858 0.0141  0.002749        +-+---+-+-+-----+--+-+--+--+-++-+----+--+----+---        0.1619
[jli01@ln3%tianhe MDD]$ egrep -w "rs910805" MDD2018_ex23andMe
20      rs910805        21248116        A       G       0.764   0.762   0.988   1.00461 0.0093  0.6201  7       ++++-+  0.0     5       0.6118   59851   113154  69115.85

AND here is the log 
[all-mtag-2.log](https://github.com/omeed-maghzian/mtag/files/3131175/all-mtag-2.log)

Best,
Xueming Yao

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

I'm surprised that `mtag` runs through in your case, because based on what you sent, your input data does not even contain the allele frequency and sample size columns. These two columns are required by `mtag`, so I could not replicate your error. Maybe you can try adding those information to your input sumstats, and specify `--freq_name`, `--n_name` and  `beta_name` in the command accordingly. 

Best,
Hui

**Comment by YaoXueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi, Hui
        the column you mentioned have added in the input file when I ran the MTAG. Because the data is limited, I only have the summary statistics,  I know the  total sample size of each trait. I set the allele frequency column as 0.5 and the sample size column same as the total sample size of each trait.  Is that the problem?Best,Xueming Yao
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Xueming Yao
                            
                    
                        
                            
                                    
                                    yaoxueming@tmu.edu.cn
                                    
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/1/2019 01:43，huilisabrina<notifications@github.com> wrote： 


Hi @YaoXueming ,
I'm surprised that mtag runs through in your case, because based on what you sent, your input data does not even contain the allele frequency and sample size columns. These two columns are required by mtag, so I could not replicate your error. Maybe you can try adding those information to your input sumstats, and specify --freq_name, --n_name and  beta_name in the command accordingly.
Best,
Hui

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

Thanks. Adding allele frequency of all 0.5 to the sumstats is not right because allele frequency is used for scaling the effect sizes, etc. You can add that information using external reference panel e.g. Hapmap or 1000 Genome. Can you `head` your input files to `mtag`? I think you sent the sample format of the raw file before, but it's better to check the data you directly pass to `mtag`. 

Best,
Hui

**Comment by YaoXueming** [comment]
Hi, Hui,

Thanks you for telling me this. Here are my input files, they are the same format,only the word or number are different among the traits, I put only one here.

[jli01@ln3%tianhe ADHD]$ head adhd-mtag
CHR SNP BP A1 A2 INFO OR SE P freq beta n
1 rs202152658 751343 A T 0.88 1.02737 0.0226 0.2333 0.5 0.0270021 53293
1 rs143225517 751756 T C 0.88 0.97336 0.0226 0.2332 0.5 -0.0270013 53293
1 rs3094315 752566 A G 0.941 0.96281 0.0194 0.05045 0.5 -0.0378992 53293
1 rs3131972 752721 A G 0.94 1.04123 0.0194 0.03696 0.5 0.0404027 53293
1 rs3131971 752894 T C 0.938 1.03987 0.0195 0.04431 0.5 0.0390957 53293
1 rs61770173 753405 A C 0.874 0.97083 0.0218 0.1738 0.5 -0.0296039 53293
1 rs3131970 753425 T C 0.874 1.02994 0.0217 0.1753 0.5 0.0295005 53293
1 rs2073814 753474 C G 0.912 1.03842 0.0196 0.05427 0.5 0.0377003 53293
1 rs2073813 753541 A G 0.882 1.03376 0.0223 0.1365 0.5 0.0332026 53293

Is there any exact suggestion to solve this problem?

Best,
Xueming Yao

**Comment by YaoXueming** [comment]
hi,  @huilisabrina ,

I used the 1000G to add the column of allele frequency,and I met a problem, not all the allele 1 and allele 2 in 1000G is same order as past input file (same order with summary statistics), the beta, n, P, n in new input file are same as summary statistics. Will this influence the result of MTAG?

This is my past input file
[jli01@ln3%tianhe ADHD]$ head adhd-mtag-2
CHR SNP BP A1 A2 SE P freq beta n
1 rs202152658 751343 A T 0.0226 0.2333 0.5 0.0270021 53293
1 rs143225517 751756 T C 0.0226 0.2332 0.5 -0.0270013 53293
1 rs3094315 752566 A G 0.0194 0.05045 0.5 -0.0378992 53293

This is my new input file
[jli01@ln3%tianhe ADHD]$ head adhd-hg19-mt-2
CHR BP SNP SE P beta n A1 A2 freq
10 10000018 rs6602381 0.0136 0.0003217 0.0487997 53293 A G 0.4662
10 100000625 rs7899632 0.0136 0.9129 -0.00150113 53293 A G 0.4483
10 100000645 rs61875309 0.0169 0.2916 0.0178006 53293 A C 0.2247

Then I select two of the common SNP to check the allele order.
[jli01@ln3%tianhe ADHD]$ tail adhd-hg19-mt-2
9:99996548 rs10981288 0.0135 0.8201 0.0030952 53293 C T 0.504
9:99996634 rs10759527 0.0135 0.8391 0.00269636 53293 T G 0.6133

[jli01@ln3%tianhe ADHD]$ egrep -w "rs10981288" adhd-mtag-2
9 rs10981288 99996548 T C 0.0135 0.8201 0.5 0.0030952 53293
[jli01@ln3%tianhe ADHD]$ egrep -w "rs10759527" adhd-mtag-2
9 rs10759527 99996634 T G 0.0135 0.8391 0.5 0.00269636 53293

As you can see, the  order is different in rs10981288 but same in  rs10759527, in this condition,  can  I use the new input files to run MTAG?

Best,
Xueming Yao

**Comment by huilisabrina** [comment]
Hi @YaoXueming ,

No you'd need to align the ref/alt allele between your input data and the reference panel. The frequency is for the allele in column `A1`, so you'd need to match them when you merge the data. 

Best,
Hui

**Comment by YaoXueming** [comment]
Hi, @huilisabrina 

Thanks you so much!

Best,
Xueming Yao
