### ISSUE TITLE
Reporting weights and correlation matrix in MTAG log file

### ISSUE THREAD

**Issue by paturley** [omeed-maghzian/mtag#7]
It would be helpful for diagnosing problems with the software if the log file reported two additional things.

1. The log file already reports Omega, it would be great if it also reported the correlation matrix implied by Omega.

2. It also would be helpful if it reported the weights assigned to each trait. This could be the weight associated with the max N or the mean N.

**Comment by huilisabrina** [comment]
Implemented in #36
