### ISSUE TITLE
KeyError: 'AAACACAAACAC'

### ISSUE THREAD

**Issue by fujilian** [omeed-maghzian/mtag#71]
Hi, I have trouble in running MTAG
The log is as follows (by the way, the a2 is effect allele in my summary statistic data)  

2019/05/25/07:02:30 PM 
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<>
<> MTAG: Multi-trait Analysis of GWAS 
<> Version: 1.0.8
<> (C) 2017 Omeed Maghzian, Raymond Walters, and Patrick Turley
<> Harvard University Department of Economics / Broad Institute of MIT and Harvard
<> GNU General Public License v3
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<> Note:  It is recommended to run your own QC on the input before using this program. 
<> Software-related correspondence: maghzian@nber.org 
<> All other correspondence: paturley@broadinstitute.org 
<><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Calling ./mtag.py \
--force  \
--se-name SE \
--p-name p-value \
--bpos-name pos \
--stream-stdout  \
--n-name N \
--a2-name a1 \
--n-min 0.0 \
--a1-name a2 \
--snp-name rsid \
--use-beta-se  \
--eaf-name af \
--sumstats R_thalamus.txt,L_thalamus.txt \
--out ./tutorial_results_thalamus 

2019/05/25/07:02:30 PM Beginning MTAG analysis...
2019/05/25/07:02:30 PM MTAG will use the provided BETA/SE columns for analyses.
2019/05/25/07:02:41 PM Read in Trait 1 summary statistics (5572549 SNPs) from R_thalamus.txt ...
2019/05/25/07:02:41 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:02:41 PM Munging Trait 1  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2019/05/25/07:02:41 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:02:41 PM Interpreting column names as follows:
2019/05/25/07:02:41 PM p-value:	p-Value
af:	Allele frequency
rsid:	Variant ID (e.g., rs number)
N:	Sample size
a1:	a2, interpreted as non-ref allele for signed sumstat.
beta:	Directional summary statistic as specified by --signed-sumstats.
a2:	a1, interpreted as ref allele for signed sumstat.
SE:	Standard errors of BETA coefficients

2019/05/25/07:02:41 PM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2019/05/25/07:02:51 PM Read 5572549 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 125339 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 439632 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
5007578 SNPs remain.
2019/05/25/07:02:54 PM Removed 4162 SNPs with duplicated rs numbers (5003416 SNPs remain).
2019/05/25/07:02:55 PM Removed 0 SNPs with N < 0.0 (5003416 SNPs remain).
2019/05/25/07:03:39 PM Median value of SIGNED_SUMSTAT was -7.8281e-05, which seems sensible.
2019/05/25/07:03:39 PM Dropping snps with null values
2019/05/25/07:03:40 PM 
Metadata:
2019/05/25/07:03:40 PM Mean chi^2 = 1.012
2019/05/25/07:03:40 PM WARNING: mean chi^2 may be too small.
2019/05/25/07:03:40 PM Lambda GC = 1.011
2019/05/25/07:03:40 PM Max chi^2 = 30.977
2019/05/25/07:03:40 PM 2 Genome-wide significant SNPs (some may have been removed by filtering).
2019/05/25/07:03:40 PM 
Conversion finished at Sat May 25 19:03:40 2019
2019/05/25/07:03:40 PM Total time elapsed: 58.94s
2019/05/25/07:03:48 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:03:48 PM Munging of Trait 1 complete. SNPs remaining:	 5008930
2019/05/25/07:03:48 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2019/05/25/07:03:48 PM Warning: The mean chi2 statistic of trait 1 is less 1.02 - MTAG estimates may be unstable.
2019/05/25/07:03:58 PM Trait 1: Dropped 5514 SNPs for duplicate values in the "snp_name" column
2019/05/25/07:04:09 PM Read in Trait 2 summary statistics (5572549 SNPs) from CHIMGEN_L_thalamus.txt ...
2019/05/25/07:04:09 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:04:09 PM Munging Trait 2  <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><
2019/05/25/07:04:09 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:04:09 PM Interpreting column names as follows:
2019/05/25/07:04:09 PM p-value:	p-Value
af:	Allele frequency
rsid:	Variant ID (e.g., rs number)
N:	Sample size
a1:	a2, interpreted as non-ref allele for signed sumstat.
beta:	Directional summary statistic as specified by --signed-sumstats.
a2:	a1, interpreted as ref allele for signed sumstat.
SE:	Standard errors of BETA coefficients

2019/05/25/07:04:09 PM Reading sumstats from provided DataFrame into memory 10000000 SNPs at a time.
2019/05/25/07:04:19 PM Read 5572549 SNPs from --sumstats file.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= None.
Removed 125339 SNPs with MAF <= 0.01.
Removed 0 SNPs with SE <0 or NaN values.
Removed 0 SNPs with out-of-bounds p-values.
Removed 439632 variants that were not SNPs. Note: strand ambiguous SNPs were not dropped.
5007578 SNPs remain.
2019/05/25/07:04:24 PM Removed 4162 SNPs with duplicated rs numbers (5003416 SNPs remain).
2019/05/25/07:04:24 PM Removed 0 SNPs with N < 0.0 (5003416 SNPs remain).
2019/05/25/07:05:08 PM Median value of SIGNED_SUMSTAT was -2.40275e-05, which seems sensible.
2019/05/25/07:05:08 PM Dropping snps with null values
2019/05/25/07:05:09 PM 
Metadata:
2019/05/25/07:05:09 PM Mean chi^2 = 1.009
2019/05/25/07:05:09 PM WARNING: mean chi^2 may be too small.
2019/05/25/07:05:09 PM Lambda GC = 1.007
2019/05/25/07:05:09 PM Max chi^2 = 27.731
2019/05/25/07:05:09 PM 0 Genome-wide significant SNPs (some may have been removed by filtering).
2019/05/25/07:05:09 PM 
Conversion finished at Sat May 25 19:05:09 2019
2019/05/25/07:05:09 PM Total time elapsed: 1.0m:0.02s
2019/05/25/07:05:18 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/05/25/07:05:18 PM Munging of Trait 2 complete. SNPs remaining:	 5008930
2019/05/25/07:05:18 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

2019/05/25/07:05:18 PM Warning: The mean chi2 statistic of trait 2 is less 1.02 - MTAG estimates may be unstable.
2019/05/25/07:05:28 PM Trait 2: Dropped 5514 SNPs for duplicate values in the "snp_name" column
2019/05/25/07:05:32 PM Dropped 757001 SNPs due to strand ambiguity, 4246415 SNPs remain in intersection after merging trait1
2019/05/25/07:05:46 PM Dropped 0 SNPs due to strand ambiguity, 4246415 SNPs remain in intersection after merging trait2
2019/05/25/07:05:46 PM ... Merge of GWAS summary statistics complete. Number of SNPs:	 4246415
2019/05/25/07:06:00 PM Using 4246415 SNPs to estimate Omega (0 SNPs excluded due to strand ambiguity)
2019/05/25/07:06:00 PM Estimating sigma..
2019/05/25/07:09:09 PM 'AAACACAAACAC'
Traceback (most recent call last):
  File "/g/jilian/software/mtag/mtag.py", line 1567, in <module>
    mtag(args)
  File "/g/jilian/software/mtag/mtag.py", line 1351, in mtag
    args.sigma_hat = estimate_sigma(DATA[not_SA], args)
  File "/g/jilian/software/mtag/mtag.py", line 468, in estimate_sigma
    rg_results =  sumstats_sig.estimate_rg(args_ldsc_rg, Logger_to_Logging())
  File "/g/jilian/software/mtag/ldsc_mod/ldscore/sumstats.py", line 442, in estimate_rg
    loop = _read_other_sumstats(args, log, None, sumstats, ref_ld_cnames,sumstats2=p2)
  File "/g/jilian/software/mtag/ldsc_mod/ldscore/sumstats.py", line 494, in _read_other_sumstats
    loop['Z2'] = _align_alleles(loop.Z2, alleles)
  File "/g/jilian/software/mtag/ldsc_mod/ldscore/sumstats.py", line 567, in _align_alleles
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
  File "/g/jilian/software/Anaconda3/envs/py2/lib/python2.7/site-packages/pandas/core/series.py", line 3194, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer
  File "/g/jilian/software/mtag/ldsc_mod/ldscore/sumstats.py", line 567, in <lambda>
    z *= (-1) ** alleles.apply(lambda y: FLIP_ALLELES[y])
KeyError: 'AAACACAAACAC'
2019/05/25/07:09:09 PM Analysis terminated from error at Sat May 25 19:09:09 2019
2019/05/25/07:09:09 PM Total time elapsed: 6.0m:38.75

what should I do?
Looking forward to your kindly reply

**Comment by paturley** [comment]
Looks to me like one of your alleles for one of your SNPs is coded as
"AAACACAAACAC" so when the software tries to align the alleles between the
two data sets, it gets confused. In your QC before passing the results into
MTAG, maybe try removing these variants and see if that fixes things.

Best,
Patrick

**Comment by fujilian** [comment]
Hi paturley ,
Thanks for your suggestions. I checked my summary datasets and LD file. There were not  SNPs coded as
"AAACACAAACAC", But when I tried to change the LD file and the error disappeared. It is strange.
Best,
Jilian

**Comment by paturley** [comment]
Ah, OK. I'm glad it seems to be working now. Feel free to close this issue
if you have no further questions.

Best,
Patrick

**Comment by fujilian** [comment]
No further questions, thank you again for your help

**Comment by siminyu0629** [comment]
@fujilian  Hi！I have met the same issue, I wonder how you fixed that? Could you tell me, please?

**Comment by paturley** [comment]
I believe they just searched their summary statistics for SNPs that had
anything other than ATC of G as the reference or alternate allele.
