### ISSUE TITLE
Error calculate MaxFDR

### ISSUE THREAD

**Issue by vackground** [omeed-maghzian/mtag#77]
Hello, we are having some problems when trying to calculate de MaxFDR MTAG. It´s results in this Error: ValueError: attempt to get argmax of an empty sequence.

The whole error is the following:

/10/03/05:20:06 PM  
2019/10/03/05:20:06 PM MTAG results saved to file.
2019/10/03/05:20:06 PM Beginning maxFDR calculations. Depending on the number of grid points specified, this might take some time...
2019/10/03/05:20:06 PM T=2
2019/10/03/05:20:06 PM Number of gridpoints to search: 0
2019/10/03/05:20:06 PM Performing grid search using 1 cores.
2019/10/03/05:20:06 PM Grid search: 10.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 20.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 30.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 40.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 50.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 60.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 70.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 80.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 90.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Grid search: 100.0 percent finished for . Time: 	0.000 min
2019/10/03/05:20:06 PM Saved calculations of fdr over grid points in ./testlnl_scz_eu_mtag_maxFDR_fdr_mat.txt
2019/10/03/05:20:06 PM <><><<>><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2019/10/03/05:20:06 PM attempt to get argmax of an empty sequence
Traceback (most recent call last):
  File "mtag.py", line 1567, in <module>
    mtag(args)
  File "mtag.py", line 1455, in mtag
    fdr(args, Ns, Zs)
  File "mtag.py", line 1269, in fdr
    ind_max = np.argmax(FDR, axis=0)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1103, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

When we tried after only with the MaxFDR option the error was the same:

Traceback (most recent call last):
  File "mtag.py", line 1563, in <module>
    fdr(args, N_mat, Z_mat)
  File "mtag.py", line 1269, in fdr
    ind_max = np.argmax(FDR, axis=0)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

Any ideas or suggestions about the error? Thank you!

Alvaro

**Comment by paturley** [comment]
It looks like you are maximizing FDR over an empty space. What is the
command you are using to run MTAG?

**Comment by vackground** [comment]
Thank you for your quick response, this is the command:

python mtag.py  \
	--sumstats testsczeu.txt,mtaglnsum.txt \
	--out ./testlnl_scz_eu_mtag_maxFDR \
	--use_beta_se \
	--n_min 0.0 \
        --stream_stdout \
        --fdr \
        --stream_stdout

**Comment by paturley** [comment]
What happens when you include the --intervals option set to 10?

**Comment by vackground** [comment]
The same. I have tried before:
python mtag.py  \
> --skip_mtag \
> --intervals 10 \
> --out ./testlnl_scz_eu_mtag_maxFDR 
Traceback (most recent call last):
  File "mtag.py", line 1563, in <module>
    fdr(args, N_mat, Z_mat)
  File "mtag.py", line 1269, in fdr
    ind_max = np.argmax(FDR, axis=0)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "//anaconda2/envs/myenv/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence

**Comment by paturley** [comment]
Hmm. Curious. Can you attach the full log file? It's not clear to me what
it going wrong from just the error.

**Comment by vackground** [comment]
Hello, I tried to rerun after update again numpy but the error continued.
This is the log file:
[testlnl_scz_eu_mtag_maxFDR.log](https://github.com/omeed-maghzian/mtag/files/3701272/testlnl_scz_eu_mtag_maxFDR.log)

Thanks!!

**Comment by paturley** [comment]
It looks like the problem is that Omega matrix contains nan values. I am a
bit surprised by this though given how powerful your GWAS summary stats
are. Have you tried running the software using the Z-N option rather than
the beta-SE options?

**Comment by vackground** [comment]
Hello, Patrick, 
I was able to run the MTAG with Z-scores without Error in Calculate the Max FDR. I attach the log file for your knowledge. MaxFDR is quite low so I understand that the results were robust.
I would like to ask two more questions. First, we used a summary statistics of one previous 3 traits MTAG as the second trait for this MTAG analysis, is there any problem with this issue? we don't have the ST of the other 3 GWAS  traits.
The other question is about the position of the traits in the summstats flag, we obtain better improvements in the results in trait 2, but our main interest was in trait 1.  Is there any change in the final MTAG results when you change the position in the analysis?

Thank you again for your help
Alvaro

[newtestlnlz.log](https://github.com/omeed-maghzian/mtag/files/3709096/newtestlnlz.log)

**Comment by paturley** [comment]
Hi Alvaro,

I can't think of why using MTAG summary statistics as the input into MTAG
for a different analysis would cause problems, but I haven't tested it
carefully.

MTAG should produce the same results no matter the order of the summary
statistics. (If you swap the order and it changes the results, let me know.
That means there is something wrong...)

Best,
Patrick
