### ISSUE TITLE
Running one binary and four continuous traits in a single analysis

### ISSUE THREAD

**Issue by Lassana1** [omeed-maghzian/mtag#78]
Hi all, 
        I have GWAS output from five traits of the same cohort. One of them in a binary trait. 
For continuous traits, my summary output has: BE and SE columns
For binary trait,my summary output has: 
Score.Stat = The score Z test statistic
Score=Value of the score function

My questions are:
1) Can I run BE,SE for some traits and Z-score for some traits in a single analysis?
2) If so, do I use Score or Score.Stat in the analysis?

Thanks so much!!!

**Comment by paturley** [comment]
Hello,

I think that in the current software, you need to use either the Z/N or the
Beta/SE framework for all input files. If you have the beta and SEs for the
continuous traits, you should be able to convert those into z-statistics.
The output of MTAG will correspond to phenotypes that have been
standardized, so they may not be in the same units as the input files.

**Comment by Lassana1** [comment]
Hi Pat, 
         Thank you. Does you mean that the summary statistics should be from GWAS that was run using standardized phenotypes?

**Comment by paturley** [comment]
No. The summary statistics that you have will work whether or not the
phenotype was standardized. But the output MTAG coefficients will
correspond to a phenotype that has been standardized even if the phenotype
for the input GWAS was not.

Best,
Patrick
