### ISSUE TITLE
Question about "same trait" analysis

### ISSUE THREAD

**Issue by vackground** [omeed-maghzian/mtag#89]
Hello Patrick,
I have a question regarding the viability of the analyses in the same trait, particularly in UK biobank. 
I am conscious of MTAG's ability to support sample overlap and analyses of different measures of the same trait as indicated in Methods but I have a concern about the way certain traits are assessed and the potential risk of violating any assumption. 
Is there any incompatibility of combining two or more traits in which one is dependent on the response of the other?
That is to say, in the case in which a case-control trait is composed of the cases of another more generic. Does it have limitations in these cases?  I understand that the correlations are not perfect in these cases and it would not be appropriate to use --perfect_gencov flag.

Thank you in advance,

Alvaro

**Comment by paturley** [comment]
Hi Alvaro,

I think you should be fine in the case you described. (At least, I can't
think of why that sort of sample overlap would cause any more problems than
any other sort of overlap.) That said, if the sampling procedure would lead
to bias in the GWAS summary statistics, MTAG won't fix that.

Best
Patrick

**Comment by vackground** [comment]
Thank you!
Alvaro
